In [132]:
import requests
import pandas as pd
import json
import re
import time
from datetime import datetime
from bs4 import BeautifulSoup
from tqdm import tqdm
#Dinámico
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

#### Mexhome

In [133]:
#Datos de la búsqueda
cookies = {
    'utm_medium': 'Organic',
    '_pk_ref.2.513e': '%5B%2220615639987%22%2C%22%22%2C1772955324%2C%22%22%5D',
    '_pk_id.2.513e': 'cd01f928f7cfbb6c.1772955324.',
    '_pk_ses.2.513e': '1',
    '_gcl_gs': '2.1.k1$i1772955322$u57769398',
    '_gcl_au': '1.1.848721531.1772955325',
    '_gid': 'GA1.2.383899273.1772955325',
    '_gac_UA-77141872-1': '1.1772955325.CjwKCAiAqprNBhB6EiwAMe3yhpndmEpxCJcsLpOu0SiLnA0pN8xxt0DRUZX6GCb4OM1LeDAd1ibkzRoCgyEQAvD_BwE',
    '_dcid': 'dcid.1.1772955324427.447369708',
    '_cs_c': '0',
    '_tt_enable_cookie': '1',
    '_ttp': '01KK65YN6GJM8JEC2P31CR92MY_.tt.1',
    '_fbp': 'fb.1.1772955325729.733738153751410255',
    '_clck': '2c725y%5E2%5Eg46%5E0%5E2258',
    '__hstc': '111012570.9e69c4a258a6a77266b632b488e08757.1772955326448.1772955326448.1772955326448.1',
    'hubspotutk': '9e69c4a258a6a77266b632b488e08757',
    '__hssrc': '1',
    '_gcl_aw': 'GCL.1772955336.CjwKCAiAqprNBhB6EiwAMe3yhpndmEpxCJcsLpOu0SiLnA0pN8xxt0DRUZX6GCb4OM1LeDAd1ibkzRoCgyEQAvD_BwE',
    'AMP_MKTG_8f1ede8e9c': 'JTdCJTdE',
    '_ga': 'GA1.2.389813916.1772955325',
    '_cs_id': '851f46a4-4a05-a8ae-efb5-0f2668566894.1772955325.1.1772956158.1772955325.1.1807119325561.1.x',
    '_uetsid': '5f7de7f01ac111f1964cc31ec0652ef0',
    '_uetvid': '5f7e34801ac111f1a93f81a51bb7ddc4',
    'cf_clearance': 'OgnVviwZnLATWkpky165yXIjPUURKB4hWscDq0VPlqY-1772956158-1.2.1.1-erRrDQ5yGD.hBPaRSoiqkASp6IPpmyjRXL1aH9AlRJ_32Znj5b9dWdRXnP0sKfpQXuBFZGKgojw4ZPk4PftPN_IqtcXVnhncSubXC6ofOrVnGHNUMLtUqgCPIkc2Kqtsgj4yAQ.KAO0ESZHz5TWY3fVIv3sH1wUN6mc17GyyB4xQnivdYv.SABb.OUMmh5WnuifrSF1PmyCsj6a9LDjqaDJIvNNQvzd34KHAAinDaXw',
    'AMP_8f1ede8e9c': 'JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJjNTBkODBiZC0zMTllLTQ1MjYtYTM5Mi04MGM3ZWQwMzBhN2ElMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzcyOTU1MzI0NTY1JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=',
    'AMP_8f1ede8e9c': 'JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJjNTBkODBiZC0zMTllLTQ1MjYtYTM5Mi04MGM3ZWQwMzBhN2ElMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzcyOTU1MzI0NTY1JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=',
    '_ga_CTS53R3DBH': 'GS2.1.s1772955325$o1$g1$t1772956160$j58$l0$h0',
    '__hssc': '111012570.4.1772955326448',
    '__cf_bm': 'DBGCpslWzvqhP87JYbFamnHjrgLUcjXAjt82wpRLQ7Q-1772956284-1.0.1.1-DsnWFvuUHoOqwNQHLijnTCIy89jmYp2KlnezrRxyyyY92OFR0JRFbJpa5LjIE5_uSRfz7tZ6sGxqPrsjMk6VLu9up7fkgNkCz5cR8MtJrmo',
    '_clsk': '1jlmhhq%5E1772956561515%5E6%5E1%5Ez.clarity.ms%2Fcollect',
    'ttcsid': '1772955325650::SfllbTjREIyGkeZXme2o.1.1772956573866.0',
    'ttcsid_D0VRTLBC77UD7ROKAVV0': '1772955325650::fFtKR46ICBPMEhQ0J1Y4.1.1772956573866.1',
    '_cs_s': '6.0.U.9.1772958451081',
}

headers = {
    'accept': 'application/json, text/plain, */*',
    'accept-language': 'es-US,es-419;q=0.9,es;q=0.8',
    'authorization': 'Bearer mh_5eb147b78b1140d1b46681ad82fbe55a095f89b605f9270c645049bc2f62f7c1',
    'priority': 'u=1, i',
    'referer': 'https://mexhome.com/properties?area=puerto-escondido&type=',
    'sec-ch-ua': '"Not:A-Brand";v="99", "Google Chrome";v="145", "Chromium";v="145"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/145.0.0.0 Safari/537.36',
    # 'cookie': 'utm_medium=Organic; _pk_ref.2.513e=%5B%2220615639987%22%2C%22%22%2C1772955324%2C%22%22%5D; _pk_id.2.513e=cd01f928f7cfbb6c.1772955324.; _pk_ses.2.513e=1; _gcl_gs=2.1.k1$i1772955322$u57769398; _gcl_au=1.1.848721531.1772955325; _gid=GA1.2.383899273.1772955325; _gac_UA-77141872-1=1.1772955325.CjwKCAiAqprNBhB6EiwAMe3yhpndmEpxCJcsLpOu0SiLnA0pN8xxt0DRUZX6GCb4OM1LeDAd1ibkzRoCgyEQAvD_BwE; _dcid=dcid.1.1772955324427.447369708; _cs_c=0; _tt_enable_cookie=1; _ttp=01KK65YN6GJM8JEC2P31CR92MY_.tt.1; _fbp=fb.1.1772955325729.733738153751410255; _clck=2c725y%5E2%5Eg46%5E0%5E2258; __hstc=111012570.9e69c4a258a6a77266b632b488e08757.1772955326448.1772955326448.1772955326448.1; hubspotutk=9e69c4a258a6a77266b632b488e08757; __hssrc=1; _gcl_aw=GCL.1772955336.CjwKCAiAqprNBhB6EiwAMe3yhpndmEpxCJcsLpOu0SiLnA0pN8xxt0DRUZX6GCb4OM1LeDAd1ibkzRoCgyEQAvD_BwE; AMP_MKTG_8f1ede8e9c=JTdCJTdE; _ga=GA1.2.389813916.1772955325; _cs_id=851f46a4-4a05-a8ae-efb5-0f2668566894.1772955325.1.1772956158.1772955325.1.1807119325561.1.x; _uetsid=5f7de7f01ac111f1964cc31ec0652ef0; _uetvid=5f7e34801ac111f1a93f81a51bb7ddc4; cf_clearance=OgnVviwZnLATWkpky165yXIjPUURKB4hWscDq0VPlqY-1772956158-1.2.1.1-erRrDQ5yGD.hBPaRSoiqkASp6IPpmyjRXL1aH9AlRJ_32Znj5b9dWdRXnP0sKfpQXuBFZGKgojw4ZPk4PftPN_IqtcXVnhncSubXC6ofOrVnGHNUMLtUqgCPIkc2Kqtsgj4yAQ.KAO0ESZHz5TWY3fVIv3sH1wUN6mc17GyyB4xQnivdYv.SABb.OUMmh5WnuifrSF1PmyCsj6a9LDjqaDJIvNNQvzd34KHAAinDaXw; AMP_8f1ede8e9c=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJjNTBkODBiZC0zMTllLTQ1MjYtYTM5Mi04MGM3ZWQwMzBhN2ElMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzcyOTU1MzI0NTY1JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=; AMP_8f1ede8e9c=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJjNTBkODBiZC0zMTllLTQ1MjYtYTM5Mi04MGM3ZWQwMzBhN2ElMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzcyOTU1MzI0NTY1JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=; _ga_CTS53R3DBH=GS2.1.s1772955325$o1$g1$t1772956160$j58$l0$h0; __hssc=111012570.4.1772955326448; __cf_bm=DBGCpslWzvqhP87JYbFamnHjrgLUcjXAjt82wpRLQ7Q-1772956284-1.0.1.1-DsnWFvuUHoOqwNQHLijnTCIy89jmYp2KlnezrRxyyyY92OFR0JRFbJpa5LjIE5_uSRfz7tZ6sGxqPrsjMk6VLu9up7fkgNkCz5cR8MtJrmo; _clsk=1jlmhhq%5E1772956561515%5E6%5E1%5Ez.clarity.ms%2Fcollect; ttcsid=1772955325650::SfllbTjREIyGkeZXme2o.1.1772956573866.0; ttcsid_D0VRTLBC77UD7ROKAVV0=1772955325650::fFtKR46ICBPMEhQ0J1Y4.1.1772956573866.1; _cs_s=6.0.U.9.1772958451081',
}

response = requests.get(
    'https://mexhome.com/wp-json/mh/v1/properties?expand=photos,location&per_page=42&area=puerto-escondido',
    cookies=cookies,
    headers=headers,
)

data=response.json()

print("Total de registros:", len(data))

Total de registros: 40

In [134]:
#Obtener los datos

oferta=[]
precio=[]
cuartos=[]
banos=[]
latitud=[]
longitud=[]
metros_cuad_const=[]
metros_cuad_terreno=[]
link=[]
tipo=[]
for propiedades in data:
    oferta.append(propiedades.get('name'))
    link.append(propiedades.get('link_es'))
    precio.append(propiedades.get('details', {}).get('property_list_price_usd'))
    cuartos.append(propiedades.get('details', {}).get('property_bedrooms'))
    banos.append(propiedades.get('details', {}).get('property_baths'))
    metros_cuad_const.append(propiedades.get('details', {}).get('property_lot_m2'))
    metros_cuad_terreno.append(propiedades.get('details', {}).get('property_total_sqft'))
    latitud.append(
    float(((propiedades.get('details') if isinstance(propiedades.get('details'), dict) else {}).get('item_location') or {}).get('lat'))
    if ((propiedades.get('details') if isinstance(propiedades.get('details'), dict) else {}).get('item_location') or {}).get('lat')
    else None
    )
    longitud.append(float(((propiedades.get('details') if isinstance(propiedades.get('details'), dict) else {}).get('item_location') or {}).get('lng'))
     if ((propiedades.get('details') if isinstance(propiedades.get('details'), dict) else {}).get('item_location') or {}).get('lng')
     else None)
    tipo.append(propiedades.get('details', {}).get('property_type'))

mexhome_df=pd.DataFrame({'oferta':oferta,'precio_usd':precio,
                         'cuartos':cuartos,
                         'metros_cuad_const':metros_cuad_const,
                            'metros_cuad_terreno':metros_cuad_terreno,
                         'banos':banos,'latitud':latitud,'longitud':longitud,
                         'link':link,
                         'tipo':tipo, "fuente":"mexhome","fecha_consulta":pd.Timestamp.now()})

#Cambiar en type Condos por Departamento, House por Casa, Land por Terreno y si no, déjalo en blanco
mexhome_df["tipo"] = mexhome_df["tipo"].replace({
    "Condos": "Departamento",
    "Houses": "Casa",
    "Land": "Terreno"
}).fillna("")
#Número de columnas
print("Número de columnas en mexhome_df:", mexhome_df.shape[1])
mexhome_df.head(5)

Número de columnas en mexhome_df: 12

,oferta,precio_usd,cuartos,metros_cuad_const,metros_cuad_terreno,banos,latitud,longitud,link,tipo,fuente,fecha_consulta
0,Vivo &#8211; Building F &#8211; 632,295000,2,,,2,NaN,NaN,https://mexhome.com/es/property/vivo-building-...,Departamento,mexhome,2026-04-06 02:09:10.130057
1,Vivo &#8211; Building H &#8211; 833,685000,4,,,3,15.915630,-97.185896,https://mexhome.com/es/property/vivo-building-...,Departamento,mexhome,2026-04-06 02:09:10.130057
2,Vivo &#8211; Villa Lots &#8211; 28,149000,,,,,15.915738,-97.182546,https://mexhome.com/es/property/vivo-villa-lot...,Terreno,mexhome,2026-04-06 02:09:10.130057
3,325 Vivo &#8211; Building C,128900,0,,,1,NaN,NaN,https://mexhome.com/es/property/325-vivo-build...,Departamento,mexhome,2026-04-06 02:09:10.130057
4,Vivo &#8211; Building E &#8211; 531,425000,3,,,2,15.915336,-97.185159,https://mexhome.com/es/property/vivo-building-...,Departamento,mexhome,2026-04-06 02:09:10.130057

In [135]:
#Obtener detalles adicionales de cada propiedad
def scrape_detalle(url, session):
    try:
        r = session.get(url, timeout=10)
        r.raise_for_status()
        soup = BeautifulSoup(r.text, "html.parser")

        # ── ZONA (breadcrumb) ──
        zona = None
        breadcrumbs = soup.select("ol.breadcrumb li span[itemprop='name']")
        if len(breadcrumbs) >= 2:
            zona = breadcrumbs[1].get_text(strip=True)

        # ── Bloque del agente ──
        agente_card = soup.select_one("div.card.card-agent")

        # ── ASESOR ──
        asesor = None
        if agente_card:
            asesor_tag = agente_card.select_one("h4.mt-0.mt-md-3 a")
            if asesor_tag:
                asesor = asesor_tag.get_text(strip=True)

        # ── CORREO ──
        correo = None
        if agente_card:
            for a in agente_card.find_all("a"):
                span = a.find("span", class_="icon-email")
                if span:
                    correo = a.get_text(strip=True)
                    break

        # ── TELÉFONO ──
        telefono = None
        if agente_card:
            for a in agente_card.find_all("a", href=True):
                if a["href"].startswith("tel:"):
                    telefono = a["href"].replace("tel:", "").strip()
                    break

        return zona, asesor, correo, telefono

    except Exception as e:
        print(f"  ✗ Error: {url} → {e}")
        return None, None, None, None

# ── Agregar columnas a tu tabla ya existente ──────────────────
session = requests.Session()
session.headers.update(headers)
session.cookies.update(cookies)

zonas, asesores, correos, telefonos = [], [], [], []

for i, url in enumerate(mexhome_df["link"]):
    print(f"[{i+1}/{len(mexhome_df)}] {url}")
    zona, asesor, correo, tel = scrape_detalle(url, session)
    zonas.append(zona)
    asesores.append(asesor)
    correos.append(correo)
    telefonos.append(tel)
    time.sleep(1.5)

mexhome_df["zona"]     = zonas
mexhome_df["asesor"]   = asesores
mexhome_df["correo"]   = correos
mexhome_df["contacto"] = telefonos
print("Número de columnas en mexhome_df con detalles:", mexhome_df.shape[1])

mexhome_df.head()

[1/40] https://mexhome.com/es/property/vivo-building-f-632/
[2/40] https://mexhome.com/es/property/vivo-building-h-833/
[3/40] https://mexhome.com/es/property/vivo-villa-lots-28/
[4/40] https://mexhome.com/es/property/325-vivo-building-c/
[5/40] https://mexhome.com/es/property/vivo-building-e-531/
[6/40] https://mexhome.com/es/property/vivo-villa-home-41-casa-sol/
[7/40] https://mexhome.com/es/property/barbarians-ocean-view-eco-retreat-center/
[8/40] https://mexhome.com/es/property/vivo-building-marino-1343/
[9/40] https://mexhome.com/es/property/vivo-villa-casa-paraiso/
[10/40] https://mexhome.com/es/property/vivo-building-laguna-1224/
[11/40] https://mexhome.com/es/property/vivo-building-marino-1311/
[12/40] https://mexhome.com/es/property/vivo-building-marino-1344/
[13/40] https://mexhome.com/es/property/vivo-villa-lots-75/
[14/40] https://mexhome.com/es/property/vivo-villa-lots-78/
[15/40] https://mexhome.com/es/property/vivo-villa-lots-24-2/
[16/40] https://mexhome.com/es/property/vivo-building-l-1223/
[17/40] https://mexhome.com/es/property/vivo-building-h-843/
[18/40] https://mexhome.com/es/property/vivo-building-b-233/
[19/40] https://mexhome.com/es/property/vivo-building-f-612/
[20/40] https://mexhome.com/es/property/vivo-building-b-216/
[21/40] https://mexhome.com/es/property/vivo-villa-lots-37-resale/
[22/40] https://mexhome.com/es/property/vivo-building-d-421-lock-off/
[23/40] https://mexhome.com/es/property/vivo-building-laguna-1252/
[24/40] https://mexhome.com/es/property/tres-aguas-villa-lots-15/
[25/40] https://mexhome.com/es/property/tres-aguas-villa-lots-10/
[26/40] https://mexhome.com/es/property/tres-aguas-villa-lots-07/
[27/40] https://mexhome.com/es/property/vivo-building-laguna-1233/
[28/40] https://mexhome.com/es/property/vivo-building-nautico-unit-1442/
[29/40] https://mexhome.com/es/property/vivo-villa-lots-1/
[30/40] https://mexhome.com/es/property/vivo-villa-lots-90/
[31/40] https://mexhome.com/es/property/vivo-building-a-141-151/
[32/40] https://mexhome.com/es/property/vivo-building-nautico-unit-1433/
[33/40] https://mexhome.com/es/property/tres-aguas-villa-lots-06/
[34/40] https://mexhome.com/es/property/tres-aguas-villa-lots-27/
[35/40] https://mexhome.com/es/property/vivo-building-b-242-resale/
[36/40] https://mexhome.com/es/property/ocn-properties-casita-studio/
[37/40] https://mexhome.com/es/property/ocn-properties-nativo-villa/
[38/40] https://mexhome.com/es/property/ocn-properties-ola-villa/
[39/40] https://mexhome.com/es/property/nautico-unit-1471/
[40/40] https://mexhome.com/es/property/vivo-building-laguna-1222/
Número de columnas en mexhome_df con detalles: 16

,oferta,precio_usd,cuartos,metros_cuad_const,metros_cuad_terreno,banos,latitud,longitud,link,tipo,fuente,fecha_consulta,zona,asesor,correo,contacto
0,Vivo &#8211; Building F &#8211; 632,295000,2,,,2,NaN,NaN,https://mexhome.com/es/property/vivo-building-...,Departamento,mexhome,2026-04-06 02:09:10.130057,Playa Palmarito,Vivianne Salgado Zetter,vivianne@mexhome.com,+52 331 536 2681
1,Vivo &#8211; Building H &#8211; 833,685000,4,,,3,15.915630,-97.185896,https://mexhome.com/es/property/vivo-building-...,Departamento,mexhome,2026-04-06 02:09:10.130057,Playa Palmarito,Vivianne Salgado Zetter,vivianne@mexhome.com,+52 331 536 2681
2,Vivo &#8211; Villa Lots &#8211; 28,149000,,,,,15.915738,-97.182546,https://mexhome.com/es/property/vivo-villa-lot...,Terreno,mexhome,2026-04-06 02:09:10.130057,Playa Palmarito,Vivianne Salgado Zetter,vivianne@mexhome.com,+52 331 536 2681
3,325 Vivo &#8211; Building C,128900,0,,,1,NaN,NaN,https://mexhome.com/es/property/325-vivo-build...,Departamento,mexhome,2026-04-06 02:09:10.130057,Playa Palmarito,Vivianne Salgado Zetter,vivianne@mexhome.com,+52 331 536 2681
4,Vivo &#8211; Building E &#8211; 531,425000,3,,,2,15.915336,-97.185159,https://mexhome.com/es/property/vivo-building-...,Departamento,mexhome,2026-04-06 02:09:10.130057,Playa Palmarito,Vivianne Salgado Zetter,vivianne@mexhome.com,+52 331 536 2681

#### OsanPuerto

In [136]:
url = "https://www.osanpuerto.com/modules/mod_properties/request.php"

headers = {
    "accept": "application/json, text/javascript, */*; q=0.01",
    "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
    "x-requested-with": "XMLHttpRequest",
    "referer": "https://www.osanpuerto.com/",
    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

data = {
    "lang": "_es",
    "type": "",
    "action": "get_properties",
    "status": "",
    "price": "",
    "currency": "",
    "q": ""
}

response = requests.post(url, headers=headers, data=data)

# Validación básica
response.raise_for_status()

json_data = response.json()

osanpuerto = pd.DataFrame(json_data["data"])
#Seleccionar name, currency, type, lat, lng
osanpuerto = osanpuerto[["name","bathrooms","bedrooms","swimming_pool","parking","price","price_usd", "location","type", "lat", "lng", "m2","agent","correo","link","near_to_beach"]]
#Renombrar columnas
osanpuerto.rename(columns={
    "location": "zona",
    "name": "oferta",
    "bathrooms": "banos",
    "bedrooms": "cuartos",
    "swimming_pool": "piscina",
    "parking": "estacionamiento",
    "price": "precio_mxn",
    "price_usd": "precio_usd",
    "currency": "moneda",
    "type": "tipo",
    "lat": "latitud",
    "lng": "longitud",
    "m2": "metros_cuad_terreno",
    "agent": "asesor",
    "correo": "correo",
    "link": "link",
    "near_to_beach": "vista_al_mar",
}, inplace=True)

#Añadir fuente y fecha de consulta
osanpuerto["fuente"] = "osanpuerto"
osanpuerto["fecha_consulta"] = pd.Timestamp.now()
print("Número de columnas en osanpuerto:", osanpuerto.shape[1])
osanpuerto.head(5)

Número de columnas en osanpuerto: 18

,oferta,banos,cuartos,piscina,estacionamiento,precio_mxn,precio_usd,zona,tipo,latitud,longitud,metros_cuad_terreno,asesor,correo,link,vista_al_mar,fuente,fecha_consulta
0,"Casa Gemelas, con Alberca y Rooftop en Puerto ...",1,1,1,1,4900000.00,274791.52,Barra de Colotepec,Departamento,15.82841670000000,-97.03516670000000,165.13,Oscar Herrera,oscar@osanpuerto.com,https://www.osanpuerto.com/es/propiedades/depa...,1,osanpuerto,2026-04-06 02:10:55.240126
1,"Terreno con Vista al Mar en Venta en El Ébano,...",0,0,0,0,1400000.00,78511.86,El Ebano,Departamento,15.84488890000000,-97.03177780000000,300.38,Antoine Volatier,antoine@osanpuerto.com,https://www.osanpuerto.com/es/propiedades/depa...,0,osanpuerto,2026-04-06 02:10:55.240126
2,"Terreno en Venta en Punta Zicatela, Puerto Esc...",0,0,0,0,11600000.00,650526.87,Punta Zicatela,Terreno,15.84191670000000,-97.04775000000000,827.94,Oscar Herrera,oscar@osanpuerto.com,https://www.osanpuerto.com/es/propiedades/terr...,1,osanpuerto,2026-04-06 02:10:55.240126
3,Terreno con vista al mar en venta en Playa Agu...,0,0,0,0,590000.00,33087.14,Agua Blanca,Terreno,15.73965939100000,-96.81210193147857,200,Antoine Volatier,antoine@osanpuerto.com,https://www.osanpuerto.com/es/propiedades/terr...,1,osanpuerto,2026-04-06 02:10:55.240126
4,Terreno con Vista al Mar en Venta en Puertecit...,0,0,0,0,874997.00,49069.75,El Puertecito,Terreno,15.74108520000000,-96.85457620000000,296.54,Antoine Volatier,antoine@osanpuerto.com,https://www.osanpuerto.com/es/propiedades/terr...,1,osanpuerto,2026-04-06 02:10:55.240126

#### RealEstate.PuertoEscondido

In [137]:
url = "https://realestate.puerto-escondido.mx/es/propiedades/"

headers = {
    "User-Agent": "Mozilla/5.0"
}

html = requests.get(url, headers=headers).text

# =========================
# EXTRAER markers
# =========================
pattern = r'googlecode_regular_vars\.markers="(\[\[.*?\]\])"'

match = re.search(pattern, html, re.DOTALL)
markers_raw = match.group(1)

markers_raw = markers_raw.replace('\\"', '"')
markers = json.loads(markers_raw)

# =========================
# PARSEAR
# =========================
rows = []

for m in markers:
    try:
        nombre = m[0]
        lat = float(m[1])
        lon = float(m[2])

        # precio
        precio = float(m[11]) if m[11] else None

        # tipo
        tipo = m[15] if len(m) > 15 else None

        # cuartos (posición 12)
        try:
            cuartos = int(m[12])
        except:
            cuartos = None

        # baños (posición 13)
        try:
            banos = int(m[13])
        except:
            banos = None
        #link
        link = m[9] if m[9] else None
        #Descripción
        descripcion = m[19] if m[19] else None

        rows.append({
            "oferta": nombre,
            "latitud": lat,
            "longitud": lon,
            "precio_mxn": precio,
            "tipo": tipo,
            "cuartos": cuartos,
            "banos": banos,
            "link": link
        })

    except Exception as e:
        print("error:", e)

# =========================
# DATAFRAME
# =========================
realestatepuerto = pd.DataFrame(rows)

#realestatepuerto["moneda"] = "MXN"
realestatepuerto["fuente"] = "realestate_puerto_escondido"
realestatepuerto["fecha_consulta"] = datetime.now()

# limpiar nombre
realestatepuerto["oferta"] = realestatepuerto["oferta"].apply(requests.utils.unquote)
#Limpiar url
realestatepuerto["link"] = realestatepuerto["link"].apply(requests.utils.unquote)


print("Total registros:", len(realestatepuerto))
print("Número de columnas en realestatepuerto:", realestatepuerto.shape[1])
realestatepuerto.head()

Total registros: 182
Número de columnas en realestatepuerto: 10

,oferta,latitud,longitud,precio_mxn,tipo,cuartos,banos,link,fuente,fecha_consulta
0,Terreno de 558m2 en La Punta,15.832888,-97.041382,7000000.0,Terreno,0,0.0,https://realestate.puerto-escondido.mx/es/prop...,realestate_puerto_escondido,2026-04-06 02:10:56.126180
1,Casa ecológica única en La Punta,15.836159,-97.043481,12480000.0,Casa,2,2.0,https://realestate.puerto-escondido.mx/es/prop...,realestate_puerto_escondido,2026-04-06 02:10:56.126180
2,Propiedad Frente al Mar de Lujo en El Puertecito,15.740076,-96.855683,28305984.0,Casa,11,NaN,https://realestate.puerto-escondido.mx/es/prop...,realestate_puerto_escondido,2026-04-06 02:10:56.126180
3,Lotes Frente al Mar en Palmarito,15.916446,-97.186960,7710000.0,Terreno,0,0.0,https://realestate.puerto-escondido.mx/es/prop...,realestate_puerto_escondido,2026-04-06 02:10:56.126180
4,Terreno con Vista al Mar en Agua Blanca,15.734264,-96.812565,1750000.0,Terreno,0,0.0,https://realestate.puerto-escondido.mx/es/prop...,realestate_puerto_escondido,2026-04-06 02:10:56.126180

In [138]:
def scrape_realestate_puerto(url, session):
    try:
        r = session.get(url, timeout=10)
        r.raise_for_status()
        soup = BeautifulSoup(r.text, "html.parser")

        # ── ZONA ──
        zona = None
        cateqs = soup.select("div.property_categs a")
        if len(cateqs) >= 2:
            zona = cateqs[1].get_text(strip=True)

        # ── ASESOR ──
        asesor = None
        asesor_tag = soup.select_one("div.col-md-7.agent_details h3 a")
        if asesor_tag:
            asesor = asesor_tag.get_text(strip=True)

        # ── TELÉFONO ──
        telefono = None
        tel_tag = soup.select_one("div.agent_detail.agent_mobile_class a[href^='tel:']")
        if tel_tag:
            telefono = tel_tag["href"].replace("tel:", "").strip()

        # ── CORREO ──
        correo = None
        correo_tag = soup.select_one("div.agent_detail.agent_email_class a[href^='mailto:']")
        if correo_tag:
            correo = correo_tag["href"].replace("mailto:", "").strip()

        # ── METROS CUADRADOS ──
        metros = None
        for div in soup.select("div.listing_detail"):
            texto = div.get_text(separator=" ", strip=True)
            if "Lot Size" in texto:
                import re
                match = re.search(r"[\d,]+", texto)
                if match:
                    metros = match.group().replace(",", "")
                break

        return zona, asesor, telefono, correo, metros

    except Exception as e:
        print(f"  ✗ Error: {url} → {e}")
        return None, None, None, None, None


# ── Agregar columnas a tu tabla ───────────────────────────────
session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
})

zonas, asesores, telefonos, correos, metros_list = [], [], [], [], []

for i, url in enumerate(realestatepuerto["link"]):
    print(f"[{i+1}/{len(realestatepuerto)}] {url}")
    zona, asesor, telefono, correo, metros = scrape_realestate_puerto(url, session)
    zonas.append(zona)
    asesores.append(asesor)
    telefonos.append(telefono)
    correos.append(correo)
    metros_list.append(metros)
    time.sleep(1.5)

realestatepuerto["zona"]               = zonas
realestatepuerto["asesor"]             = asesores
realestatepuerto["contacto"]           = telefonos
realestatepuerto["correo"]             = correos
realestatepuerto["metros_cuad_terreno"] = metros_list
print("Número de columnas en realestatepuerto con detalles:", realestatepuerto.shape[1])
realestatepuerto.head()

[1/182] https://realestate.puerto-escondido.mx/es/properties/terreno-de-558m2-en-la-punta/
[2/182] https://realestate.puerto-escondido.mx/es/properties/casa-ecologica-unica-en-la-punta/
[3/182] https://realestate.puerto-escondido.mx/es/properties/propiedad-frente-al-mar-de-lujo-en-el-puertecito/
[4/182] https://realestate.puerto-escondido.mx/es/properties/lotes-frente-al-mar-en-palmarito/
[5/182] https://realestate.puerto-escondido.mx/es/properties/terreno-con-vista-al-mar-en-agua-blanca/
[6/182] https://realestate.puerto-escondido.mx/es/properties/propiedad-con-negocio-vacacional-operando-en-la-punta/
[7/182] https://realestate.puerto-escondido.mx/es/properties/departamentos-modernos-cerca-del-aeropuerto/
[8/182] https://realestate.puerto-escondido.mx/es/properties/casa-de-inversion-premium-en-punta/
[9/182] https://realestate.puerto-escondido.mx/es/properties/incomparable-exclusiva-propiedad-de-lujo-frente-al-mar/
[10/182] https://realestate.puerto-escondido.mx/es/properties/villas-de-estilo-mediterraneo-junto-a-la-punta/
[11/182] https://realestate.puerto-escondido.mx/es/properties/terreno-con-vista-privilegiada-en-emiliano-zapata/
[12/182] https://realestate.puerto-escondido.mx/es/properties/villas-de-lujo-frente-al-mar/
[13/182] https://realestate.puerto-escondido.mx/es/properties/inversion-hotelera-a-pasos-del-mar-en-zipolite/
[14/182] https://realestate.puerto-escondido.mx/es/properties/terrenos-con-vista-al-mar/
[15/182] https://realestate.puerto-escondido.mx/es/properties/resort-boutique-para-inversion-en-tamarindos/
[16/182] https://realestate.puerto-escondido.mx/es/properties/terreno-en-esquina-cerca-de-la-punta/
[17/182] https://realestate.puerto-escondido.mx/es/properties/terreno-panoramico-el-venado/
[18/182] https://realestate.puerto-escondido.mx/es/properties/oportunidad-de-inversion-en-terreno-costero-en-el-tomatal/
[19/182] https://realestate.puerto-escondido.mx/es/properties/apartamentos-boutique-cerca-del-mar-en-tamarindos/
[20/182] https://realestate.puerto-escondido.mx/es/properties/residencia-moderna-cerca-del-mar-en-la-barra-de-colotepec/
[21/182] https://realestate.puerto-escondido.mx/es/propiedades/el-nido-la-punta/
[22/182] https://realestate.puerto-escondido.mx/es/properties/inversion-de-hostal-en-pleno-funcionamiento-en-rinconada/
[23/182] https://realestate.puerto-escondido.mx/es/properties/residencia-frente-al-mar-de-lujo-en-costa-cumana/
[24/182] https://realestate.puerto-escondido.mx/es/properties/terreno-frente-al-mar-con-cabanas-ecologicas/
[25/182] https://realestate.puerto-escondido.mx/es/properties/departamentos-premium-con-vistas-al-mar/
[26/182] https://realestate.puerto-escondido.mx/es/properties/retiro-tranquilo-de-dos-departamentos/
[27/182] https://realestate.puerto-escondido.mx/es/properties/terreno-premium-cerca-del-mar-en-la-barra/
[28/182] https://realestate.puerto-escondido.mx/es/properties/exclusiva-propiedad-cerca-del-mar-puertecito/
[29/182] https://realestate.puerto-escondido.mx/es/properties/casa-oasis-en-la-naturaleza-de-el-tomatal/
[30/182] https://realestate.puerto-escondido.mx/es/properties/refugio-de-bambu-con-vistas-al-mar/
[31/182] https://realestate.puerto-escondido.mx/es/properties/condominios-exclusivos-cerca-del-mar/
[32/182] https://realestate.puerto-escondido.mx/es/properties/terreno-increible-en-la-bomba/
[33/182] https://realestate.puerto-escondido.mx/es/properties/lotes-exclusivos-en-palmarito/
[34/182] https://realestate.puerto-escondido.mx/es/properties/lote-de-1-hectarea-a-unos-pasos-de-la-playa-el-venado-roca-blanca/
[35/182] https://realestate.puerto-escondido.mx/es/properties/inversion-premium-en-punta-zicatela/
[36/182] https://realestate.puerto-escondido.mx/es/properties/terreno-con-vista-al-mar-en-la-barra-de-navidad/
[37/182] https://realestate.puerto-escondido.mx/es/properties/pequeno-refugio-moderno-frente-al-mar/
[38/182] https://realestate.puerto-escondido.mx/es/properties/oportunidad-de-inversion-frente-al-mar/
[39/182] https://realestate.puerto-escondido.mx/es/properties/elegante-hogar-en-bacocho/
[40/182] https://realestate.puerto-escondido.mx/es/properties/santuario-moderno-de-vida-costera/
[41/182] https://realestate.puerto-escondido.mx/es/properties/casa-moderna-en-playa-venado/
[42/182] https://realestate.puerto-escondido.mx/es/properties/dos-lotes-premium-cerro-hermoso-pie-de-playa/
[43/182] https://realestate.puerto-escondido.mx/es/properties/residencias-con-vista-al-mar-en-barra-de-colotepec-2/
[44/182] https://realestate.puerto-escondido.mx/es/properties/terreno-junto-al-rio-en-la-barra-de-navidad/
[45/182] https://realestate.puerto-escondido.mx/es/properties/terreno-residencial-en-la-barra-de-colotepec/
[46/182] https://realestate.puerto-escondido.mx/es/properties/50717/
[47/182] https://realestate.puerto-escondido.mx/es/properties/departamentos-premium-con-vista-al-mar-en-la-punta/
[48/182] https://realestate.puerto-escondido.mx/es/properties/lote-con-vistas-al-mar-en-la-barra-de-colotepec/
[49/182] https://realestate.puerto-escondido.mx/es/properties/lote-tranquilo-cerca-de-playas-virgenes-en-agua-blanca/
[50/182] https://realestate.puerto-escondido.mx/es/properties/lote-con-vista-al-mar-en-miramar-bajos-de-chila/
[51/182] https://realestate.puerto-escondido.mx/es/properties/impresionante-casa-con-vistas-al-mar-en-zicatela/
[52/182] https://realestate.puerto-escondido.mx/es/properties/eco-cabanas-cerca-de-playa-mermejita/
[53/182] https://realestate.puerto-escondido.mx/es/properties/residencia-frente-al-mar-en-el-palmarito/
[54/182] https://realestate.puerto-escondido.mx/es/properties/hermosa-villa-en-la-punta-puerto-escondido/
[55/182] https://realestate.puerto-escondido.mx/es/properties/refugio-moderno-frente-al-mar/
[56/182] https://realestate.puerto-escondido.mx/es/properties/residencia-de-lujo-en-la-barra/
[57/182] https://realestate.puerto-escondido.mx/es/properties/amplia-propiedad-de-inversion-en-la-punta-puerto-escondido/
[58/182] https://realestate.puerto-escondido.mx/es/properties/amplia-propiedad-con-potencial-de-expansion/
[59/182] https://realestate.puerto-escondido.mx/es/properties/exclusiva-residencia-multifamiliar-frente-al-mar-en-puertecito/
[60/182] https://realestate.puerto-escondido.mx/es/properties/villa-de-9-recamaras-en-ubicacion-ideal/
[61/182] https://realestate.puerto-escondido.mx/es/properties/moderna-casa-en-carrizalillo/
[62/182] https://realestate.puerto-escondido.mx/es/properties/villas-exclusivas-en-preventa-puerto-escondido/
[63/182] https://realestate.puerto-escondido.mx/es/properties/casa-de-lujo-con-vistas-al-mar-en-tierra-blanca/
[64/182] https://realestate.puerto-escondido.mx/es/properties/lotes-boutique-cerca-de-la-playa/
[65/182] https://realestate.puerto-escondido.mx/es/properties/villa-de-lujo-frente-al-mar-2/
[66/182] https://realestate.puerto-escondido.mx/es/properties/terreno-con-vista-al-mar-cerca-de-la-punta/
[67/182] https://realestate.puerto-escondido.mx/es/properties/estudios-y-casas-cerca-del-mar/
[68/182] https://realestate.puerto-escondido.mx/es/properties/elegante-casa-de-4-recamaras-con-rooftop-y-amenidades-premium/
[69/182] https://realestate.puerto-escondido.mx/es/properties/moderna-casa-de-3-recamaras-con-amenidades-en-playa-palmarito/
[70/182] https://realestate.puerto-escondido.mx/es/properties/casa-moderna-con-amenidades-premium/
[71/182] https://realestate.puerto-escondido.mx/es/properties/eco-retiro-la-punta/
[72/182] https://realestate.puerto-escondido.mx/es/properties/casa-tropical-con-alberca-y-guesthouse/
[73/182] https://realestate.puerto-escondido.mx/es/properties/casas-de-1-y-2-dormitorios-con-vistas-al-mar/
[74/182] https://realestate.puerto-escondido.mx/es/properties/lotes-con-vista-al-mar-en-barra-de-colotepec/
[75/182] https://realestate.puerto-escondido.mx/es/properties/casas-ecologicas-cerca-de-zicatela/
[76/182] https://realestate.puerto-escondido.mx/es/properties/increible-casa-de-1-habitacion-en-la-punta/
[77/182] https://realestate.puerto-escondido.mx/es/properties/hostal-con-increible-potencial-en-zicatela/
[78/182] https://realestate.puerto-escondido.mx/es/properties/condominios-de-lujo-moderno-en-playa-manzanillo/
[79/182] https://realestate.puerto-escondido.mx/es/properties/46325/
[80/182] https://realestate.puerto-escondido.mx/es/properties/lotes-exclusivos-en-la-barra-de-colotepec/
[81/182] https://realestate.puerto-escondido.mx/es/properties/casa-con-vista-al-mar-y-gran-potencial/
[82/182] https://realestate.puerto-escondido.mx/es/properties/villa-frente-al-mar-en-el-puertecito/
[83/182] https://realestate.puerto-escondido.mx/es/properties/residencias-elegantes-con-vista-al-mar/
[84/182] https://realestate.puerto-escondido.mx/es/properties/villa-de-lujo-frente-al-mar/
[85/182] https://realestate.puerto-escondido.mx/es/properties/casa-moderna-cerca-de-playa-zicatela/
[86/182] https://realestate.puerto-escondido.mx/es/properties/casa-versatil-cerca-de-playa-carrizalillo/
[87/182] https://realestate.puerto-escondido.mx/es/properties/casa-con-vista-al-mar-en-mazunte/
[88/182] https://realestate.puerto-escondido.mx/es/properties/apartamentos-modernos-y-tranquilos-en-linda-vista/
[89/182] https://realestate.puerto-escondido.mx/es/properties/casa-tranquila-en-la-punta/
[90/182] https://realestate.puerto-escondido.mx/es/properties/espectacular-propiedad-con-vista-al-mar-y-dos-viviendas-independientes/
[91/182] https://realestate.puerto-escondido.mx/es/properties/villas-modernas-a-pasos-de-zicatela/
[92/182] https://realestate.puerto-escondido.mx/es/properties/villa-moderna-con-terraza-y-vista-al-mar/
[93/182] https://realestate.puerto-escondido.mx/es/properties/condominios-de-lujo-en-punta-zicatela/
[94/182] https://realestate.puerto-escondido.mx/es/properties/dos-amplios-terrenos-con-vista-al-mar/
[95/182] https://realestate.puerto-escondido.mx/es/properties/terreno-cerca-del-mercado-de-zicatela/
[96/182] https://realestate.puerto-escondido.mx/es/properties/increible-propiedad-en-venta-en-la-punta-puerto-escondido/
[97/182] https://realestate.puerto-escondido.mx/es/properties/3-lotes-en-punta-zicatela-puerto-escondido/
[98/182] https://realestate.puerto-escondido.mx/es/properties/condominios-de-lujo-con-espectacular-vista/
[99/182] https://realestate.puerto-escondido.mx/es/properties/terreno-en-zona-privilegiada-de-bacocho/
[100/182] https://realestate.puerto-escondido.mx/es/properties/lujoso-condominio-con-vista-al-mar-puerto-escondido/
[101/182] https://realestate.puerto-escondido.mx/es/properties/terreno-exclusivo-cerca-de-la-playa/
[102/182] https://realestate.puerto-escondido.mx/es/properties/villa-de-playa-en-tierra-blanca-puerto-escondido/
[103/182] https://realestate.puerto-escondido.mx/es/properties/lotes-vista-al-mar-tierra-blanc/
[104/182] https://realestate.puerto-escondido.mx/es/properties/lote-frente-al-mar-playa-encantada/
[105/182] https://realestate.puerto-escondido.mx/es/properties/departamentos-eco-friendly-en-manzanillo/
[106/182] https://realestate.puerto-escondido.mx/es/properties/maravilloso-terreno-en-la-barra-de-colotepec/
[107/182] https://realestate.puerto-escondido.mx/es/properties/confort-y-exclusividad-apartamentos-a-pocos-pasos-de-la-playa/
[108/182] https://realestate.puerto-escondido.mx/es/properties/exclusivos-departamentos-en-zicatela/
[109/182] https://realestate.puerto-escondido.mx/es/properties/departamento-de-dos-recaramas-en-playa-manzanillo/
[110/182] https://realestate.puerto-escondido.mx/es/properties/lote-de-490-m2-de-excelente-ubicacion-en-rinconada/
[111/182] https://realestate.puerto-escondido.mx/es/properties/inversion-ideal-terreno-sustentable-en-el-tomatal/
[112/182] https://realestate.puerto-escondido.mx/es/properties/inversion-ideal-en-punta-zicatela/
[113/182] https://realestate.puerto-escondido.mx/es/properties/lote-680m2-con-vista-al-mar-a-la-venta-en-emiliano-zapata/
[114/182] https://realestate.puerto-escondido.mx/es/properties/villa-de-lujo-sostenible-en-rancho-neptuno/
[115/182] https://realestate.puerto-escondido.mx/es/properties/loft-de-lujo-con-impresionante-vista-al-mar/
[116/182] https://realestate.puerto-escondido.mx/es/properties/proyecto-de-condominios-vista-al-mar-a-unos-pasos-de-la-punta/
[117/182] https://realestate.puerto-escondido.mx/es/properties/exclusivo-retiro-costero/
[118/182] https://realestate.puerto-escondido.mx/es/properties/terreno-con-vista-al-mar-en-mazunte/
[119/182] https://realestate.puerto-escondido.mx/es/properties/amplia-propiedad-frente-al-mar/
[120/182] https://realestate.puerto-escondido.mx/es/properties/casa-moderna-con-piscina-a-minutos-del-aeropuerto/
[121/182] https://realestate.puerto-escondido.mx/es/properties/piedeplayapalmarito/
[122/182] https://realestate.puerto-escondido.mx/es/properties/moderna-casa-costera-en-la-punta/
[123/182] https://realestate.puerto-escondido.mx/es/properties/terreno-frente-al-mar-potencial-ilimitado/
[124/182] https://realestate.puerto-escondido.mx/es/properties/terreno-elevado-con-vista-al-mar-en-mazunte/
[125/182] https://realestate.puerto-escondido.mx/es/properties/casa-costera-con-piscina-en-la-punta/
[126/182] https://realestate.puerto-escondido.mx/es/properties/40228/
[127/182] https://realestate.puerto-escondido.mx/es/properties/oportunidad-unica-ultimos-terrenos-en-el-corazon-de-puerto-escondido/
[128/182] https://realestate.puerto-escondido.mx/es/properties/lotes-con-impresionante-vista-al-mar-y-montana/
[129/182] https://realestate.puerto-escondido.mx/es/properties/casa-acogedora-a-minutos-de-las-mejores-playas-de-puerto-escondido/
[130/182] https://realestate.puerto-escondido.mx/es/properties/casa-vista-hermosa-paraiso-de-doble-uso-con-vista-al-mar/
[131/182] https://realestate.puerto-escondido.mx/es/properties/espectacular-villa-costera-en-puerto-escondido/
[132/182] https://realestate.puerto-escondido.mx/es/properties/penthouse-frente-al-mar/
[133/182] https://realestate.puerto-escondido.mx/es/properties/lote-residencial-en-palmarito/
[134/182] https://realestate.puerto-escondido.mx/es/properties/pie-de-playa-en-roca-blanca/
[135/182] https://realestate.puerto-escondido.mx/es/properties/vista-punta/
[136/182] https://realestate.puerto-escondido.mx/es/properties/terreno-con-acceso-a-la-playa-en-santa-elena/
[137/182] https://realestate.puerto-escondido.mx/es/properties/casa-con-vista-al-oceano-de-5-recamaras-en-barra-de-colotepec/
[138/182] https://realestate.puerto-escondido.mx/es/properties/grande-propiedad-en-la-punta-zicatela/
[139/182] https://realestate.puerto-escondido.mx/es/properties/terreno-calle-nayarit-en-la-punta/
[140/182] https://realestate.puerto-escondido.mx/es/properties/lotes-asombrosos-en-barra-de-colotepec/
[141/182] https://realestate.puerto-escondido.mx/es/properties/terreno-con-vista-al-mar-en-santa-elena/
[142/182] https://realestate.puerto-escondido.mx/es/properties/terreno-privilegiado-cerca-de-la-playa-en-la-barra/
[143/182] https://realestate.puerto-escondido.mx/es/properties/terreno-con-vista-al-mar-cerca-del-mercado-zicatela/
[144/182] https://realestate.puerto-escondido.mx/es/properties/terreno-comercial-en-charco-seco/
[145/182] https://realestate.puerto-escondido.mx/es/properties/villa-de-lujo-frente-a-la-playa-en-la-barra/
[146/182] https://realestate.puerto-escondido.mx/es/properties/villas-de-lujo-cerca-de-playa-la-punta/
[147/182] https://realestate.puerto-escondido.mx/es/properties/condominios-de-lujo-con-vista-al-mar/
[148/182] https://realestate.puerto-escondido.mx/es/properties/casa-oaxaca-pie-de-playa/
[149/182] https://realestate.puerto-escondido.mx/es/properties/casa-retiro-pacifico-de-playa/
[150/182] https://realestate.puerto-escondido.mx/es/properties/duplex-colorido-en-colina/
[151/182] https://realestate.puerto-escondido.mx/es/properties/espectacular-condominio-con-vista-al-mar-y-alberca/
[152/182] https://realestate.puerto-escondido.mx/es/properties/espectacular-hogar-casa-amarillo/
[153/182] https://realestate.puerto-escondido.mx/es/properties/impresionante-villa-frente-al-mar-en-playa-palmaritos-casa-huizache/
[154/182] https://realestate.puerto-escondido.mx/es/properties/neptuno-villa/
[155/182] https://realestate.puerto-escondido.mx/es/properties/villa-zicatela-2/
[156/182] https://realestate.puerto-escondido.mx/es/properties/terreno-frente-al-mar-de-2060m2-playa-encantada/
[157/182] https://realestate.puerto-escondido.mx/es/properties/condominio-con-vistas-al-mar-en-la-barra-de-colotepec/
[158/182] https://realestate.puerto-escondido.mx/es/properties/punta-mar-complejo-residencial-en-playa-delfines-puerto-escondido/
[159/182] https://realestate.puerto-escondido.mx/es/properties/lote-con-ubicacion-privilegiada-en-el-corazon-de-la-punta/
[160/182] https://realestate.puerto-escondido.mx/es/properties/ubicacion-privilegiada-lotes-en-la-punta-de-zicatela/
[161/182] https://realestate.puerto-escondido.mx/es/properties/luxury-condominium-in-playa-zicatela-puerto-escondido/
[162/182] https://realestate.puerto-escondido.mx/es/properties/increibles-condominios-5-min-del-aeropuerto/
[163/182] https://realestate.puerto-escondido.mx/es/properties/magnificos-10-lotes-a-la-venta-en-cerro-de-la-vieja-playa-delfin/
[164/182] https://realestate.puerto-escondido.mx/es/properties/condo-hotel-boutique-punta/
[165/182] https://realestate.puerto-escondido.mx/es/properties/ultimos-condominios-pie-de-playa-la-punta/
[166/182] https://realestate.puerto-escondido.mx/es/properties/desarrollo-exclusivo-en-la-barra-de-colotepec/
[167/182] https://realestate.puerto-escondido.mx/es/properties/lote-de-4440-m2-a-pie-de-playa-en-venta-en-el-puertecito/
[168/182] https://realestate.puerto-escondido.mx/es/properties/oportunidad-en-santa-elena-residencial-mangata/
[169/182] https://realestate.puerto-escondido.mx/es/properties/4-increibles-hectareas-con-vistas-al-mar-en-mazunte-oaxaca/
[170/182] https://realestate.puerto-escondido.mx/es/properties/villa-pie-playa-preventa-en-roca-blanca-puerto-escondido/
[171/182] https://realestate.puerto-escondido.mx/es/properties/lote-de-una-hectarea-frente-a-la-playa-en-el-venado-roca-blanca/
[172/182] https://realestate.puerto-escondido.mx/es/properties/playa-terreno-venado/
[173/182] https://realestate.puerto-escondido.mx/es/properties/lote-palmarito-puerto/
[174/182] https://realestate.puerto-escondido.mx/es/properties/casa-playa/
[175/182] https://realestate.puerto-escondido.mx/es/properties/restaurante-a-rentar-en-chacahua-gran-oportunidad/
[176/182] https://realestate.puerto-escondido.mx/es/properties/lotes-a-4-min-del-aeropuerto-muy-cerca-de-la-playa/
[177/182] https://realestate.puerto-escondido.mx/es/properties/punta-cocos-lotes-en-palmarito/
[178/182] https://realestate.puerto-escondido.mx/es/properties/real-bellat-residencial-lotes-en-palmarito/
[179/182] https://realestate.puerto-escondido.mx/es/properties/lotes-en-playa-palmarito-2/
[180/182] https://realestate.puerto-escondido.mx/es/properties/lotes-en-playa-palmarito/
[181/182] https://realestate.puerto-escondido.mx/es/properties/tierra-blanca-terreno-grande/
[182/182] https://realestate.puerto-escondido.mx/es/properties/tierrablancavistaalmar/
Número de columnas en realestatepuerto con detalles: 15

,oferta,latitud,longitud,precio_mxn,tipo,cuartos,banos,link,fuente,fecha_consulta,zona,asesor,contacto,correo,metros_cuad_terreno
0,Terreno de 558m2 en La Punta,15.832888,-97.041382,7000000.0,Terreno,0,0.0,https://realestate.puerto-escondido.mx/es/prop...,realestate_puerto_escondido,2026-04-06 02:10:56.126180,La Punta,Benjamin Cruz,5219541510426,realestate@puerto-escondido.mx,558
1,Casa ecológica única en La Punta,15.836159,-97.043481,12480000.0,Casa,2,2.0,https://realestate.puerto-escondido.mx/es/prop...,realestate_puerto_escondido,2026-04-06 02:10:56.126180,La Punta,Arika Nagy,5219541510426,arika@puerto-escondido.mx,277
2,Propiedad Frente al Mar de Lujo en El Puertecito,15.740076,-96.855683,28305984.0,Casa,11,NaN,https://realestate.puerto-escondido.mx/es/prop...,realestate_puerto_escondido,2026-04-06 02:10:56.126180,Puertecito,Benjamin Cruz,5219541510426,realestate@puerto-escondido.mx,9500
3,Lotes Frente al Mar en Palmarito,15.916446,-97.186960,7710000.0,Terreno,0,0.0,https://realestate.puerto-escondido.mx/es/prop...,realestate_puerto_escondido,2026-04-06 02:10:56.126180,Playa Palmarito,Benjamin Cruz,5219541510426,realestate@puerto-escondido.mx,1285
4,Terreno con Vista al Mar en Agua Blanca,15.734264,-96.812565,1750000.0,Terreno,0,0.0,https://realestate.puerto-escondido.mx/es/prop...,realestate_puerto_escondido,2026-04-06 02:10:56.126180,Agua Blanca,Arika Nagy,5219541510426,arika@puerto-escondido.mx,510

#### Century21

In [139]:
URL = "https://century21mexico.com/busqueda/en-estado_oaxaca/en-municipio_san-pedro-mixtepec-juquila/en-colonia_san-pedro-mixtepec-juquila-puerto-escondido"

# ==============================
# DRIVER
# ==============================
options = Options()
options.add_argument("--headless=new")
options.add_argument("--window-size=1920,1080")

driver = webdriver.Chrome(options=options)
wait = WebDriverWait(driver, 20)

driver.get(URL)

# esperar a que rendericen las cards reales
wait.until(
    EC.presence_of_element_located(
        (By.CSS_SELECTOR, "div.card.mb-4.shadow")
    )
)

time.sleep(2)

# ==============================
# HTML RENDERIZADO
# ==============================
html = driver.page_source
driver.quit()

# ==============================
# PARSEAR HTML
# ==============================
soup = BeautifulSoup(html, "html.parser")

cards = soup.select("div.card.mb-4.shadow")

rows = []

for card in cards:
    # titulo
    titulo_tag = card.select_one("h5.card-title")
    titulo = titulo_tag.get_text(" ", strip=True) if titulo_tag else None

    # zona
    zona = None
    subtitle_tag = card.select_one("div.card-subtitle")
    if subtitle_tag:
        texto = subtitle_tag.get_text(strip=True)
    # Toma todo lo que está antes de "Puerto Escondido"
        match = re.search(r"^(.+?)\s+Puerto Escondido", texto)
        if match:
            zona = match.group(1).strip()
        else:
            zona = texto.split()[0]  # fallback: primera palabra
    
    # link
    link = None
    link_tag = card.select_one("a[href^='/propiedad/']")
    if link_tag:
        link = "https://century21mexico.com" + link_tag["href"]


    # --------------------------
    # precio
    # --------------------------
    precio = None
    texto_card = card.get_text(" ", strip=True)

    m_precio = re.search(r"\$[\d,]+(?:\.\d+)?\s*MXN", texto_card)
    if m_precio:
        precio_txt = m_precio.group(0)
        precio = float(
            precio_txt.replace("$", "")
                      .replace(",", "")
                      .replace("MXN", "")
                      .strip()
        )

    # --------------------------
    # m² terreno y construcción
    # --------------------------
    metros_cuad_terreno = None
    metros_cuad_const = None

    m_terreno = re.search(r"([\d,]+)\s*m²T", texto_card)
    m_const   = re.search(r"([\d,]+)\s*m²C", texto_card)

    if m_terreno:
        metros_cuad_terreno = float(m_terreno.group(1).replace(",", ""))

    if m_const:
        metros_cuad_const = float(m_const.group(1).replace(",", ""))

    rows.append({
        "oferta": titulo,
        "precio_mxn": precio,
        "metros_cuad_terreno": metros_cuad_terreno,
        "metros_cuad_const": metros_cuad_const,
        "zona": zona,
        "link": link
    })

century21 = pd.DataFrame(rows)
#Añadir hora de consulta
century21["fecha_consulta"] = pd.Timestamp.now()
#Añadir fuente 
century21["fuente"] = "century21_mexico"
#century21["moneda"] = "MXN"
century21["asesor"] = "Enrique Alcaraz Vázquez"
century21["contacto"] = "+52 958 106 6206"
century21["correo"] = "enrique@c21procasaplus.com"

century21.head()

,oferta,precio_mxn,metros_cuad_terreno,metros_cuad_const,zona,link,fecha_consulta,fuente,asesor,contacto,correo
0,En venta - Terreno en venta en Puerto Escondid...,9574230.0,1126.0,0.0,Crotos,https://century21mexico.com/propiedad/532637_t...,2026-04-06 02:16:24.136724,century21_mexico,Enrique Alcaraz Vázquez,+52 958 106 6206,enrique@c21procasaplus.com
1,En venta - Terreno en venta en Puerto Escondid...,8514110.0,1002.0,0.0,Crotos,https://century21mexico.com/propiedad/531107_t...,2026-04-06 02:16:24.136724,century21_mexico,Enrique Alcaraz Vázquez,+52 958 106 6206,enrique@c21procasaplus.com

#### Grupo Escondido PXM

In [140]:
url = "https://www.grupoescondidopxm.mx/propiedades"

# ==============================
# DESCARGAR HTML Y LEER JSON WIX
# ==============================
html = requests.get(url).text
soup = BeautifulSoup(html, "html.parser")

script = soup.find("script", {"id": "wix-warmup-data"})
data = json.loads(script.string)

updates = data["platform"]["ssrPropsUpdates"]

# ==============================
# REPEATER UI
# ==============================
items = updates[0]["comp-maldqg5c"]["items"]

flat = {}
for d in updates[1:]:
    flat.update(d)

# ==============================
# BUSCAR DATA REAL POR item_id
# ==============================
def buscar_por_item_id(obj, item_id):
    """
    Busca recursivamente un diccionario cuyo key sea exactamente item_id.
    """
    if isinstance(obj, dict):
        for k, v in obj.items():
            if k == item_id and isinstance(v, dict):
                return v

            found = buscar_por_item_id(v, item_id)
            if found is not None:
                return found

    elif isinstance(obj, list):
        for v in obj:
            found = buscar_por_item_id(v, item_id)
            if found is not None:
                return found

    return None


# ==============================
# HELPER PARA georeferencedLocation
# ==============================
def parse_geo(geo):
    lat, lon = None, None

    if not geo:
        return lat, lon

    if isinstance(geo, str):
        try:
            lat, lon = map(float, geo.split(","))
        except:
            pass

    elif isinstance(geo, dict):
        try:
            lat = float(geo.get("latitude")) if geo.get("latitude") is not None else None
            lon = float(geo.get("longitude")) if geo.get("longitude") is not None else None
        except:
            lat, lon = None, None

    return lat, lon


# ==============================
# EXTRAER TABLA
# ==============================
rows = []

for item_id in items:

    # -------- titulo --------
    titulo_html = flat.get(f"comp-maldqg68__{item_id}", {}).get("html", "")
    titulo = BeautifulSoup(titulo_html, "html.parser").get_text(strip=True)

    # -------- precio --------
    precio_html = flat.get(f"comp-maldqg6l1__{item_id}", {}).get("html", "")
    precio_txt = BeautifulSoup(precio_html, "html.parser").get_text(strip=True)
    precio = float(re.sub(r"[^\d]", "", precio_txt)) if precio_txt else None

    #Links
    
    link_data = flat.get(f"comp-maldqg5y1__{item_id}", {})
    link = None
    if isinstance(link_data, dict):
        link = link_data.get("link", {}).get("href")
    
    if not link:
        link_html = link_data.get("html", "")
        link_soup = BeautifulSoup(link_html, "html.parser")
        link_tag = link_soup.find("a", href=True)
        link = link_tag["href"] if link_tag else None
    

    # -------- data real exacta por item_id --------
    real = buscar_por_item_id(data, item_id)

    lat = lon = area = None

    if isinstance(real, dict):
        lat, lon = parse_geo(real.get("georeferencedLocation"))
        area = real.get("totalArea")

        # fallback por si viniera en location
        if (lat is None or lon is None) and isinstance(real.get("location"), dict):
            try:
                lat = float(real["location"].get("latitude")) if real["location"].get("latitude") is not None else lat
                lon = float(real["location"].get("longitude")) if real["location"].get("longitude") is not None else lon
            except:
                pass

    rows.append({
        
        "oferta": titulo,
        "precio_mxn": precio,
        "latitud": lat,
        "longitud": lon,
        "metros_cuad_terreno": area,
        "link": link
    })

pxm = pd.DataFrame(rows)
#Añadir hora de consulta
pxm["fecha_consulta"] = pd.Timestamp.now()
#Añadir fuente 
pxm["fuente"] = "grupo escondido pxm"
print("Número de columnas en pxm:", pxm.shape[1])
pxm

Número de columnas en pxm: 8

,oferta,precio_mxn,latitud,longitud,metros_cuad_terreno,link,fecha_consulta,fuente
0,Jardines de San Pedro 1 Fraccionamiento,270000.0,15.974462,-97.071363,200,https://www.grupoescondidopxm.mx/ficha-tecnica...,2026-04-06 02:16:24.787369,grupo escondido pxm
1,Jardines de San Pedro 2 Fraccionamiento,230000.0,15.974062,-97.073911,200,https://www.grupoescondidopxm.mx/ficha-tecnica...,2026-04-06 02:16:24.787369,grupo escondido pxm
2,Acali Residencial Fraccionamiento,625000.0,15.891492,-97.041049,250,https://www.grupoescondidopxm.mx/ficha-tecnica...,2026-04-06 02:16:24.787369,grupo escondido pxm
3,Costazul Residencial,225000.0,15.936324,-97.151532,180,https://www.grupoescondidopxm.mx/ficha-tecnica...,2026-04-06 02:16:24.787369,grupo escondido pxm
4,Atardecer Lotificación,160000.0,15.891492,-97.041049,200,https://www.grupoescondidopxm.mx/ficha-tecnica...,2026-04-06 02:16:24.787369,grupo escondido pxm
5,Tabachin Lotificación,120000.0,15.778228,-96.828050,200,https://www.grupoescondidopxm.mx/ficha-tecnica...,2026-04-06 02:16:24.787369,grupo escondido pxm
6,Las Parotas Lotificación,60000.0,15.804826,-96.832489,200,https://www.grupoescondidopxm.mx/ficha-tecnica...,2026-04-06 02:16:24.787369,grupo escondido pxm

#### Pincali

In [141]:
from matplotlib.pyplot import table


def scrape_pincali():
    
    # -----------------------------
    # Consultation date
    # -----------------------------
    consultation_date = datetime.now()
    
    # -----------------------------
    # Operation mapping
    # -----------------------------
    
    all_tables = []

    # -----------------------------
    # Loop pages
    # -----------------------------
    for i in tqdm(range(1, 5), desc="Scrapeando Pincali"):
        
        # -----------------------------
        # URL
        # -----------------------------
        url = f"https://www.pincali.com/inmuebles/propiedades-en-venta?geolocation=%255B%255B14.89015257266123%252C%2520-96.7086217718429%255D%252C%2520%255B15.938592100304156%252C%2520-95.75770589646189%255D%255D&page={i}"
        
        response = requests.get(url, headers=headers)
        soup = BeautifulSoup(response.text, "html.parser")
        
        basic_data = soup.find_all("li", class_="property__component")
        
        # -----------------------------
        # Lists of data
        # -----------------------------
        name, bedrooms, bathrooms, latitude, longitude, street, region, locality, price, surface, links = [], [], [], [], [], [], [], [], [], [], []
        
        # -----------------------------
        # Loop through each property and extract data
        # -----------------------------
        for elementos in basic_data:
            
            price_tag = elementos.find("li", class_="price")
            price.append(price_tag.get_text(strip=True) if price_tag else None)
            
            link=None
            link_tag = elementos.find("a", class_="property__content property-content d-block")
            if link_tag and link_tag.has_attr("href"):
                link = "https://www.pincali.com" + link_tag["href"]
            links.append(link)

            
            name_tag = elementos.find("div", class_="title")
            name.append(name_tag.get_text(strip=True) if name_tag else None)
            
            lat = elementos.get("data-lat")
            lng = elementos.get("data-long")
            
            latitude.append(float(lat) if lat else None)
            longitude.append(float(lng) if lng else None)
            
            location_tag = elementos.find("div", class_="location")
            
            if location_tag:
                location_text = location_tag.get_text(strip=True)
                street.append(location_text)
                
                partes = [p.strip() for p in location_text.split(",")]
                locality.append(partes[-1] if len(partes) > 0 else None)
                region.append(partes[-2] if len(partes) > 1 else None)
            else:
                street.append(None)
                region.append(None)
                locality.append(None)
            
            rec = None
            bath = None
            sup = None
            
            features = elementos.find("div", class_="features")
            
            if features:
                for item in features.find_all("div"):
                    texto = item.get_text(strip=True).lower()
                    
                    numero = re.search(r"\d+", texto)
                    numero = int(numero.group()) if numero else None
                    
                    if "rec" in texto:
                        rec = numero
                    elif "bañ" in texto:
                        bath = numero
                    elif "m²" in texto or "m2" in texto:
                        sup = numero
            
            bedrooms.append(rec)
            bathrooms.append(bath)
            surface.append(sup)
            
        
        # -----------------------------
        # DataFrame for page
        # -----------------------------
        table = pd.DataFrame({
            "oferta": name,
            "precio": price,
            "metros_cuad_const": surface,
            "cuartos": bedrooms,
            "banos": bathrooms,
            "latitud": latitude,
            "longitud": longitude,
            "fecha_consulta": consultation_date,
            "link": links
        })
        
        all_tables.append(table)

    # -----------------------------
    # Final DataFrame
    # -----------------------------
    table = pd.concat(all_tables, ignore_index=True)
    table["fuente"] = "Pincali"
    table["moneda"] = table["precio"].str.extract(r"(MXN|USD)")
    table["precio"] = (
    table["precio"]
    .str.replace(r"[^\d.,]", "", regex=True)   # quita letras y símbolos
    .str.replace(",", "")                     # quita comas de miles
    .astype(float)
)
    # Después de crear la columna moneda y limpiar precio, separa en dos columnas:
    table["precio_mxn"] = table.apply(lambda r: r["precio"] if r["moneda"] == "MXN" else None, axis=1)
    table["precio_usd"] = table.apply(lambda r: r["precio"] if r["moneda"] == "USD" else None, axis=1)

    # Elimina las columnas originales
    table.drop(columns=["precio", "moneda"], inplace=True)
    
    return table

In [142]:
pincali_data= scrape_pincali()
print("Total registros:", len(pincali_data))
print("Número de columnas en pincali_data:", pincali_data.shape[1])
pincali_data.head()

Scrapeando Pincali: 100%|██████████| 4/4 [00:04<00:00,  1.19s/it]

Total registros: 161
Número de columnas en pincali_data: 11

,oferta,metros_cuad_const,cuartos,banos,latitud,longitud,fecha_consulta,link,fuente,precio_mxn,precio_usd
0,"Terreno con Vista al Mar | Zipolite | 1,468 m²...",1.0,NaN,NaN,15.663858,-96.514201,2026-04-06 02:16:24.819164,https://www.pincali.com/inmueble/terreno-con-v...,Pincali,10000000.0,NaN
1,Terreno en Condominio con Vista al Mar | Puert...,248.0,NaN,NaN,15.673660,-96.479120,2026-04-06 02:16:24.819164,https://www.pincali.com/inmueble/terreno-en-co...,Pincali,2243000.0,NaN
2,vendo terreno con vista al mar en Puerto Angel...,7.0,NaN,NaN,15.740944,-96.468645,2026-04-06 02:16:24.819164,https://www.pincali.com/inmueble/vendo-terreno...,Pincali,25893720.0,NaN
3,"Puerto Escondido, departamento en venta con un...",101.0,2.0,2.0,15.834007,-96.319949,2026-04-06 02:16:24.819164,https://www.pincali.com/inmueble/puerto-escond...,Pincali,NaN,319000.0
4,Departamento en venta en Balcones Tangolunda,110.0,2.0,2.0,15.775289,-96.097798,2026-04-06 02:16:24.819164,https://www.pincali.com/inmueble/departamento-...,Pincali,NaN,395000.0

#### Gr8 Real Estate

In [176]:
url = "https://gr8-realestate.com/azul-escondido/"

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

html = requests.get(url, headers=headers).text
soup = BeautifulSoup(html, "html.parser")

# =========================
# 1. NOMBRE Y PRECIO
# =========================
nombre, precio = None, None

for script in soup.find_all("script", {"type": "application/ld+json"}):
    try:
        data = json.loads(script.text)
        if "@graph" in data:
            for item in data["@graph"]:
                if item.get("@type") == "WebPage":
                    nombre = item.get("name")
                    desc = item.get("description", "")
                    m = re.search(r"\$([\d,]+)", desc)
                    if m:
                        precio = int(m.group(1).replace(",", ""))
    except:
        pass

# =========================
# 2. IFRAME Y COORDENADAS
# =========================
iframe = soup.find("iframe", src=lambda x: x and "maps.google.com" in x)

if iframe is None:
    raise ValueError("No se encontró iframe de Google Maps")

src = iframe["src"]

# Realizamos el request a la URL del iframe para obtener el JS interno
iframe_html = requests.get(src, headers=headers).text

# Extraemos las coordenadas usando el patrón [latitud, longitud] que vimos en el response text
# Buscamos el patrón de números decimales dentro de corchetes
match = re.search(r'\[(-?\d+\.\d+),(-?\d+\.\d+)\]', iframe_html)

if match:
    lat = float(match.group(1))
    lon = float(match.group(2))
else:
    lat, lon = None, None

# ── TELÉFONO ──
telefono = None
for a in soup.find_all("a", href=True):
    if "api.whatsapp.com/send" in a["href"]:
        match = re.search(r"phone=(\d+)", a["href"])
        if match:
            telefono = "+" + match.group(1)
        break



# =========================
# 6. DF FINAL
# =========================
gr8 = pd.DataFrame([{
    "oferta": nombre,
    "precio_mxn": precio,
    "latitud": lat,
    "longitud": lon
}])
gr8["contacto"] = telefono
gr8["asesor"] = "Marcela Molina"

#Añadir fuente y fecha de consulta
gr8["fuente"] = "gr8_realestate"
gr8["fecha_consulta"] = pd.Timestamp.now()
gr8["link"] = url
#gr8["moneda"] = "MXN"
gr8

,oferta,precio_mxn,latitud,longitud,contacto,asesor,fuente,fecha_consulta,link
0,Azul Escondido Terrenos en Preventa en Puerto ...,780000,15.799661,-96.943204,+5218138009004,Marcela Molina,gr8_realestate,2026-04-06 02:39:05.777400,https://gr8-realestate.com/azul-escondido/

In [144]:
# ===================================
# CONFIG
# ===================================
options = Options()
options.add_argument("--headless=new")
options.add_argument("user-agent=Mozilla/5.0")

driver = webdriver.Chrome(options=options)

url = "https://www.matronarealestate.com/propiedades"
driver.get(url)

time.sleep(5)

rows = []

# ===================================
# SOLO HEADERS QUE SON PROYECTOS
# ===================================
titulos = driver.find_elements(By.XPATH, "//h1 | //h2 | //h3")

for t in titulos:
    nombre = t.text.strip()

    if not re.search(r"residencial|fraccionamiento", nombre, re.IGNORECASE):
        continue

    try:
        ul = t.find_element(By.XPATH, "following::ul[1]")
        items = ul.find_elements(By.TAG_NAME, "li")

        precio = None
        lotes = None
        ubicacion = None

        for item in items:
            texto = item.text.strip()

            # Precio
            if "$" in texto:
                precio = texto

            # Lotes — "Lotes desde 200m2"
            match_lotes = re.search(r"Lotes\s+desde\s+([\d,]+)\s*m", texto, re.IGNORECASE)
            if match_lotes:
                lotes = match_lotes.group(1).replace(",", "")

            # Ubicación — "Ubicación: Rosedal"
            match_ubicacion = re.search(r"Ubicaci[oó]n[:\s]+(.+)", texto, re.IGNORECASE)
            if match_ubicacion:
                ubicacion = match_ubicacion.group(1).strip()

        if precio:
            rows.append({
                "oferta"              : nombre,
                "precio_mxn"         : precio,
                "metros_cuad_terreno": lotes,
                "zona"               : ubicacion,
            })

    except:
        continue

driver.quit()



matrona= pd.DataFrame(rows).drop_duplicates()
#Añadir fuente y fecha de consulta
matrona["fuente"] = "Matrona Real Estate"
matrona["correo"] = "contacto@matronarealestate.com"
matrona["contacto"] = "(+52) 954 136 0864"
matrona["fecha_consulta"] = pd.Timestamp.now()
#matrona["moneda"] = "MXN"
#Dejar solo número en precio_mxn
matrona["precio_mxn"] = matrona["precio_mxn"].str.replace(r"[^\d]", "", regex=True).astype(float)
matrona["tipo"] = "Terreno"
matrona["link"] = "https://www.matronarealestate.com/propiedades"
print("Número de columnas en matrona:", matrona.shape[1])
matrona.head()

Número de columnas en matrona: 10

,oferta,precio_mxn,metros_cuad_terreno,zona,fuente,correo,contacto,fecha_consulta,tipo,link
0,Residencial Pacífico,340000.0,200,Rosedal,Matrona Real Estate,contacto@matronarealestate.com,(+52) 954 136 0864,2026-04-06 02:16:41.582107,Terreno,https://www.matronarealestate.com/propiedades
1,Fraccionamiento Cielo Ventanilla,320000.0,216,Ventanilla,Matrona Real Estate,contacto@matronarealestate.com,(+52) 954 136 0864,2026-04-06 02:16:41.582107,Terreno,https://www.matronarealestate.com/propiedades
2,Natura Residencial,110000.0,200,Tomatal,Matrona Real Estate,contacto@matronarealestate.com,(+52) 954 136 0864,2026-04-06 02:16:41.582107,Terreno,https://www.matronarealestate.com/propiedades
3,Residencial Punta Lago,60002.0,200,None,Matrona Real Estate,contacto@matronarealestate.com,(+52) 954 136 0864,2026-04-06 02:16:41.582107,Terreno,https://www.matronarealestate.com/propiedades
4,Residencial Zelena,40002.0,213,None,Matrona Real Estate,contacto@matronarealestate.com,(+52) 954 136 0864,2026-04-06 02:16:41.582107,Terreno,https://www.matronarealestate.com/propiedades

#### Puerto Property

In [145]:
url="https://puertoproperty.com/portofolio/"
r=requests.get(url, headers=headers)
soup=BeautifulSoup(r.text, "html.parser")
tabla=soup.find("table")
filas=tabla.find_all("tr")
rows = []
for fila in filas[1:]:
    celdas = fila.find_all("td")
    
    if len(celdas) >= 4:
        oferta = celdas[0].get_text(strip=True)
        detalle = celdas[1].get_text(strip=True)
        
        size = celdas[2].get_text(strip=True)
        price = celdas[3].get_text(strip=True)
        
        # limpiar números
        size = float(size.replace(",", "")) if size else None
        price = float(price.replace(",", "")) if price else None

        rows.append({
            "oferta": oferta,
            "detalle": detalle,
            "metros_cuad_const": size,
            "precio_usd": price
        })

puertoproperty = pd.DataFrame(rows)

# metadatos
puertoproperty["fuente"] = "Puerto Property"
puertoproperty["fecha_consulta"] = pd.Timestamp.now()
#puertoproperty["moneda"] = "USD"
puertoproperty["tipo"] = "Terreno"
puertoproperty["link"] = "https://puertoproperty.com/portofolio/"
print("Número de columnas en puertoproperty:", puertoproperty.shape[1])

puertoproperty.head()

Número de columnas en puertoproperty: 8

,oferta,detalle,metros_cuad_const,precio_usd,fuente,fecha_consulta,tipo,link
0,12a,Sold,1739.07,521721.0,Puerto Property,2026-04-06 02:16:42.192663,Terreno,https://puertoproperty.com/portofolio/
1,13a,Sold,1747.90,524370.0,Puerto Property,2026-04-06 02:16:42.192663,Terreno,https://puertoproperty.com/portofolio/
2,34,Sold,1971.40,591420.0,Puerto Property,2026-04-06 02:16:42.192663,Terreno,https://puertoproperty.com/portofolio/
3,35,Sold,1834.63,550389.0,Puerto Property,2026-04-06 02:16:42.192663,Terreno,https://puertoproperty.com/portofolio/
4,36,Sold,1814.27,544281.0,Puerto Property,2026-04-06 02:16:42.192663,Terreno,https://puertoproperty.com/portofolio/

#### Inmobisur

In [146]:
url = "https://inmobisur.mx/#desarrollos"
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers)
response.encoding = 'utf-8' 
soup = BeautifulSoup(response.text, "html.parser")

# ── TELÉFONO global del sitio ──
telefono = None
for a in soup.find_all("a", href=True):
    if "api.whatsapp.com/send" in a["href"]:
        match = re.search(r"phone=(\d+)", a["href"])
        if match:
            telefono = "+" + match.group(1)
        break
bloques = soup.find_all("div", {"data-framer-component-type": "RichTextContainer"})
data = []

for bloque in bloques:
    texto = bloque.get_text(separator="\n").strip()
    
    if "Plusvalía" in texto or "lotes" in texto:
        # Unimos todo para facilitar la búsqueda con regex
        limpio = " ".join([l.strip() for l in texto.split('\n') if l.strip()])
        
        # 1. Tiempo: Buscamos solo el número y la unidad (meses/semanas)
        # Captura: un número y la palabra que le sigue inmediatamente
        tiempo_match = re.search(r'comercialización:\s*(\d+\s*(?:meses|semanas|mes))', limpio, re.I)
        
        # 2. Metros cuadrados: Buscamos el patrón de m²
        # Algunos tienen dos valores (total | comercializado), capturamos el bloque numérico
        m2_match = re.search(r'([\d,]+\s*(?:\|\s*[\d,]+\s*)?m²)', limpio)
        
        # 3. Plusvalía, Lotes e Inversionistas (reutilizados)
        plusvalia_match = re.search(r'Plusvalía:\s*([\d\–\-%\s]+)', limpio)
        lotes_match = re.search(r'(\d+)\s*lotes', limpio)
        inv_match = re.search(r'(\d+)\s*inversionistas', limpio)

        lineas = texto.split('\n')
        registro = {
            "oferta": lineas[0].strip(),
            "zona": lineas[1].strip() if len(lineas) > 1 else None,
            "metros_cuad_terreno": m2_match.group(1).replace('m²', '').strip() if m2_match else None,
            "lotes": lotes_match.group(1) if lotes_match else None,
            "inversionistas": inv_match.group(1) if inv_match else None,
            "contacto": telefono,
            #"plusvalia": plusvalia_match.group(1).strip() if plusvalia_match else None,
            #"tiempo_comercializacion": tiempo_match.group(1) if tiempo_match else None
        }
        data.append(registro)

inmobisur = pd.DataFrame(data).drop_duplicates(subset=['oferta', 'zona']).reset_index(drop=True)
#Añadir fuente y fecha de consulta
inmobisur["fuente"] = "Inmobisur"
inmobisur["zona"] = inmobisur["zona"].apply(
    lambda z: z.split(",")[0].strip() if isinstance(z, str) else z
)
inmobisur["fecha_consulta"] = pd.Timestamp.now()
inmobisur["link"] = "https://inmobisur.mx/#desarrollos"
print("Número de columnas en inmobisur:", inmobisur.shape[1])
inmobisur.head()

Número de columnas en inmobisur: 9

,oferta,zona,metros_cuad_terreno,lotes,inversionistas,contacto,fuente,fecha_consulta,link
0,2019 - ÍNDIGO Residencial,Puertecito,"9,185",36,30,+9541230481,Inmobisur,2026-04-06 02:16:43.156799,https://inmobisur.mx/#desarrollos
1,2020 - CIAN Residencial,Santa María Colotepec,"29,996",96,70,+9541230481,Inmobisur,2026-04-06 02:16:43.156799,https://inmobisur.mx/#desarrollos
2,2021 - AQUA Residencial I,Agua Blanca,"25,467 | 21,091",90,70,+9541230481,Inmobisur,2026-04-06 02:16:43.156799,https://inmobisur.mx/#desarrollos
3,2019 - ÍNDIGO Residencial,Puertecito,"9,185",36,30,+9541230481,Inmobisur,2026-04-06 02:16:43.156799,https://inmobisur.mx/#desarrollos
4,2021 - TEAL Residencial,Agua Blanca,"4,299 | 38,119",192,125,+9541230481,Inmobisur,2026-04-06 02:16:43.156799,https://inmobisur.mx/#desarrollos

#### Madre Ceiba

In [148]:
#No usar headless 
options = Options()
driver = webdriver.Chrome(options=options)

try:
    driver.get("https://www.madreceibaproperties.com/es/propiedades")
    time.sleep(4) # Espera a que cargue la primera tanda

    # --- ESTRATEGIA DE SCROLL POR ETAPAS ---
    registros_actuales = 0
    intentos_sin_cambio = 0
    
    while True:
        # Bajamos un poco (ejemplo: 1000 pixeles)
        driver.execute_script("window.scrollBy(0, 1000);")
        time.sleep(1.5) # Pausa breve para que el JS reaccione
        
        # Contamos cuántas tarjetas hay en el DOM en este momento
        soup_temp = BeautifulSoup(driver.page_source, "html.parser")
        conteo = len(soup_temp.find_all("div", class_="destacados_title-wrapper"))
        
        print(f"Cargados hasta ahora: {conteo} registros...")

        if conteo > registros_actuales:
            registros_actuales = conteo
            intentos_sin_cambio = 0
        else:
            intentos_sin_cambio += 1
            # Si después de 8 scrolls no sube el número, ya llegamos al final real
            if intentos_sin_cambio > 8: 
                break

    # --- EXTRACCIÓN FINAL ---
    final_soup = BeautifulSoup(driver.page_source, "html.parser")
    resultados = final_soup.find_all("div", class_="destacados_item")

    lista_propiedades = []
    for res in resultados:
        # Tu lógica de extracción corregida
        ubicacion = res.find("div", attrs={"fs-list-field": "ubicacion"})
        precio = res.find("div", class_="text-group")
        titulo = res.find("h3")
        tipo = res.find("div", attrs={"fs-list-field": "propiedad"}) 
        superficie_terreno = res.find("div", attrs={"fs-list-field": "superficie"})
        superficie_construccion = res.find("div", attrs={"fs-list-field": "construccion"})
        cuartos = res.find("div", attrs={"fs-list-field": "recamaras"})
        link= res.find("a", class_="w-inline-block")

        lista_propiedades.append({
            "zona": ubicacion.get_text(strip=True) if ubicacion else None,
            "precio_mxn": precio.get_text(strip=True) if precio else None,
            "oferta": titulo.get_text(strip=True) if titulo else None,
            "tipo": tipo.get_text(strip=True) if tipo else None,
            "metros_cuad_terreno": superficie_terreno.get_text(strip=True) if superficie_terreno else None,
            "metros_cuad_const": superficie_construccion.get_text(strip=True) if superficie_construccion else None,
            "cuartos": cuartos.get_text(strip=True) if cuartos else None,
            "link": link["href"] if link and link.has_attr("href") else None
        })

    madre_ceiba = pd.DataFrame(lista_propiedades)
    
    # Limpieza final
    madre_ceiba['precio_mxn'] = madre_ceiba['precio_mxn'].str.replace(r'[^\d]', '', regex=True)
    madre_ceiba['precio_mxn'] = pd.to_numeric(madre_ceiba['precio_mxn'], errors='coerce')

finally:
    driver.quit()

print("Total de registros extraídos:", len(madre_ceiba))
#Añadir fuente y fecha de consulta
madre_ceiba["fuente"] = "Madre Ceiba Properties"
madre_ceiba["fecha_consulta"] = pd.Timestamp.now()
#A cada link añadirle "https://www.madreceibaproperties.com/"
madre_ceiba["link"] = madre_ceiba["link"].apply(lambda x: f"https://www.madreceibaproperties.com{x}" if pd.notnull(x) else None)
#añadir correo y teléfono de contacto
madre_ceiba["correo"] = "info@madreceibaproperties.com"
madre_ceiba["contacto"] = "(+52) 954-103-9496"
madre_ceiba["asesor"] = None
print("Número de columnas en madre_ceiba:", madre_ceiba.shape[1])
madre_ceiba.head()

Cargados hasta ahora: 20 registros...
Cargados hasta ahora: 20 registros...
Cargados hasta ahora: 20 registros...
Cargados hasta ahora: 20 registros...
Cargados hasta ahora: 40 registros...
Cargados hasta ahora: 40 registros...
Cargados hasta ahora: 40 registros...
Cargados hasta ahora: 40 registros...
Cargados hasta ahora: 40 registros...
Cargados hasta ahora: 60 registros...
Cargados hasta ahora: 60 registros...
Cargados hasta ahora: 60 registros...
Cargados hasta ahora: 60 registros...
Cargados hasta ahora: 80 registros...
Cargados hasta ahora: 80 registros...
Cargados hasta ahora: 80 registros...
Cargados hasta ahora: 80 registros...
Cargados hasta ahora: 80 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Cargados hasta ahora: 97 registros...
Total de registros extraídos: 97
Número de columnas en madre_ceiba: 13

,zona,precio_mxn,oferta,tipo,metros_cuad_terreno,metros_cuad_const,cuartos,link,fuente,fecha_consulta,correo,contacto,asesor
0,Barra de Colotepec,1450000,Terreno Lomas de La Barra,Terreno,400,None,,https://www.madreceibaproperties.com/es/propie...,Madre Ceiba Properties,2026-04-06 02:20:06.589584,info@madreceibaproperties.com,(+52) 954-103-9496,None
1,Barra de Colotepec,1900000,Terreno a unos pasos del mar,Terreno,200,None,,https://www.madreceibaproperties.com/es/propie...,Madre Ceiba Properties,2026-04-06 02:20:06.589584,info@madreceibaproperties.com,(+52) 954-103-9496,None
2,Barra de Navidad,500000,Terreno Barra de Navidad,Terreno,200,None,,https://www.madreceibaproperties.com/es/propie...,Madre Ceiba Properties,2026-04-06 02:20:06.589584,info@madreceibaproperties.com,(+52) 954-103-9496,None
3,Lindavista,1900000,Terreno Lindavista,Terreno,250,None,,https://www.madreceibaproperties.com/es/propie...,Madre Ceiba Properties,2026-04-06 02:20:06.589584,info@madreceibaproperties.com,(+52) 954-103-9496,None
4,San Pedro Mixtepec,22000000,Casa en Construcción en Palmarito,Casa,1200,None,3,https://www.madreceibaproperties.com/es/propie...,Madre Ceiba Properties,2026-04-06 02:20:06.589584,info@madreceibaproperties.com,(+52) 954-103-9496,None

#### Viva México Inmobiliaria

In [149]:
# 1. Definimos la lista de fuentes con su respectivo tipo
fuentes = [
    {"url": "https://www.vivamexicoinmobiliaria.com/casas-departamentos-en-venta-puerto-escondido/", "tipo": "casas y departamentos"},
    {"url": "https://www.vivamexicoinmobiliaria.com/terrenos-en-venta-puerto-escondido/", "tipo": "terrenos"},
    {"url": "https://www.vivamexicoinmobiliaria.com/desarrollos-en-puerto-escondido/", "tipo": "desarrollos"}
]

headers = {"User-Agent": "Mozilla/5.0"}
rows = []

# 2. Iteramos sobre cada fuente
for fuente in fuentes:
    r = requests.get(fuente["url"], headers=headers)
    soup = BeautifulSoup(r.text, "html.parser")
    
    # Buscamos los contenedores
    resultados = soup.find_all("div", class_="elementor-widget-wrap elementor-element-populated")

    for res in resultados:
        titulo_tag = res.find("h2", class_="elementor-heading-title elementor-size-default")
        precio_tag = res.find("span", class_="woocommerce-Price-amount amount")
        detalle = res.find("div", class_="elementor-element elementor-element-05e92d1 elementor-widget elementor-widget-text-editor")
        link= res.find("a", class_="elementor-button elementor-button-link elementor-size-sm")
        
        if titulo_tag and precio_tag:
            rows.append({
                "oferta": titulo_tag.get_text(strip=True),
                "precio_mxn": precio_tag.get_text(strip=True),
                #"detalle": detalle.get_text(separator=" ", strip=True) if detalle else "",
                "tipo": fuente["tipo"],
                "link": link["href"] if link and link.has_attr("href") else None
            })

# 3. Creación del DataFrame y limpieza
vivamexico = pd.DataFrame(rows)

# Eliminar duplicados considerando el tipo por si una oferta aparece en dos categorías
vivamexico = vivamexico.drop_duplicates(subset=['oferta', 'precio_mxn', 'tipo']).reset_index(drop=True)

# Añadir metadatos
vivamexico["fuente"] = "Viva Mexico Inmobiliaria"
vivamexico["fecha_consulta"] = pd.Timestamp.now().strftime("%Y-%m-%d %H:%M:%S")

print(f"Total de registros capturados: {len(vivamexico)}")
#Eliminar símbolos de precio y convertir a numérico
vivamexico['precio_mxn'] = vivamexico['precio_mxn'].str.replace(r'[^\d.]', '', regex=True)
vivamexico['precio_mxn'] = pd.to_numeric(vivamexico['precio_mxn'], errors='coerce')
#Añadir correo
vivamexico["correo"] = "contacto@vivamexicoinmobiliaria.com"
print("Número de columnas en vivamexico:", vivamexico.shape[1])
vivamexico.head()

Total de registros capturados: 78
Número de columnas en vivamexico: 7

,oferta,precio_mxn,tipo,link,fuente,fecha_consulta,correo
0,"Casa en Residencial Don Goyo, Punta Zicatela",8800000.0,casas y departamentos,https://www.vivamexicoinmobiliaria.com/product...,Viva Mexico Inmobiliaria,2026-04-06 02:20:09,contacto@vivamexicoinmobiliaria.com
1,"Casa Selva Mar, Playa San Agustinillo, Oaxaca",5500000.0,casas y departamentos,https://www.vivamexicoinmobiliaria.com/product...,Viva Mexico Inmobiliaria,2026-04-06 02:20:09,contacto@vivamexicoinmobiliaria.com
2,"Departamento Altavista– Vista al mar, diseño y...",309000.0,casas y departamentos,https://www.vivamexicoinmobiliaria.com/product...,Viva Mexico Inmobiliaria,2026-04-06 02:20:09,contacto@vivamexicoinmobiliaria.com
3,"Casa Punta del Cielo, Playa San Agustinillo, O...",25000000.0,casas y departamentos,https://www.vivamexicoinmobiliaria.com/product...,Viva Mexico Inmobiliaria,2026-04-06 02:20:09,contacto@vivamexicoinmobiliaria.com
4,"Casa El Faro, Puerto Angel",13500000.0,casas y departamentos,https://www.vivamexicoinmobiliaria.com/product...,Viva Mexico Inmobiliaria,2026-04-06 02:20:09,contacto@vivamexicoinmobiliaria.com

In [150]:
def scrape_vivamexico(url, session):
    try:
        r = session.get(url, timeout=10)
        r.raise_for_status()
        soup = BeautifulSoup(r.text, "html.parser")

        # ── ASESOR (segundo h2.elementor-heading-title) ──
        asesor = None
        asesor_tags = soup.select("h2.elementor-heading-title")
        if len(asesor_tags) >= 2:
            asesor = asesor_tags[1].get_text(strip=True)

        # ── TELÉFONO (desde href de WhatsApp) ──
        telefono = None
        for a in soup.find_all("a", href=True):
            if "wa.me/" in a["href"]:
                match = re.search(r"wa\.me\/(\+?\d+)", a["href"])
                if match:
                    telefono = "+" + match.group(1).lstrip("+")
                break

        # ── ZONA (segunda <p> en elementor-widget-container) ──
        zona = None
        containers = soup.select("div.elementor-widget-container p")
        if len(containers) >= 2:
            texto = containers[1].get_text(strip=True)
            texto_limpio = re.sub(r'[^\w\s,]', '', texto).strip()
            zona = texto_limpio.split(",")[0].strip()

        return asesor, telefono, zona

    except Exception as e:
        print(f"  ✗ Error: {url} → {e}")
        return None, None, None


# ── Loop ─────────────────────────────────────────────────────
session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
})

asesores, telefonos, zonas = [], [], []

for i, url in enumerate(vivamexico["link"]):
    print(f"[{i+1}/{len(vivamexico)}] {url}")
    asesor, telefono, zona = scrape_vivamexico(url, session)
    asesores.append(asesor)
    telefonos.append(telefono)
    zonas.append(zona)
    time.sleep(1.5)

vivamexico = vivamexico.copy()
vivamexico.loc[:, "asesor"]   = asesores
vivamexico.loc[:, "contacto"] = telefonos
vivamexico.loc[:, "zona"]     = zonas
print("Número de columnas en vivamexico con detalles:", vivamexico.shape[1])
vivamexico.head()

[1/78] https://www.vivamexicoinmobiliaria.com/producto/villa-en-residencial-don-goyo-en-la-punta-zicatela/
[2/78] https://www.vivamexicoinmobiliaria.com/producto/casa-selva-mar-vista-y-acceso-directo-al-mar/
[3/78] https://www.vivamexicoinmobiliaria.com/producto/departamento-altavista-la-barra-colotepec/
[4/78] https://www.vivamexicoinmobiliaria.com/producto/casa-punta-del-cielo-vista-al-mar-playa-san-agustinillo/
[5/78] https://www.vivamexicoinmobiliaria.com/producto/casa-faro-en-playa-puerto-angel-oaxaca/
[6/78] https://www.vivamexicoinmobiliaria.com/producto/vendida-casas-brisas-diamante-en-puerto-escondido/
[7/78] https://www.vivamexicoinmobiliaria.com/producto/casa-frente-al-mar-en-playa-delfines-puerto-escondido/
[8/78] https://www.vivamexicoinmobiliaria.com/producto/casa-cocos-frente-al-mar-en-costa-cumana/
[9/78] https://www.vivamexicoinmobiliaria.com/producto/casa-paloma-en-playa-la-barra-casa-de-playa/
[10/78] https://www.vivamexicoinmobiliaria.com/producto/casas-diamante-con-alberca-privada/
[11/78] https://www.vivamexicoinmobiliaria.com/producto/casa-onix-en-playa-zicatela-casa-2-departamentos/
[12/78] https://www.vivamexicoinmobiliaria.com/producto/departamento-altavista-en-barra-de-navidad-frente-al-mar/
[13/78] https://www.vivamexicoinmobiliaria.com/producto/casa-marias-en-venta-punta-zicatela-oaxaca/
[14/78] https://www.vivamexicoinmobiliaria.com/producto/casa-parota-frente-al-mar-en-playa-tomatal/
[15/78] https://www.vivamexicoinmobiliaria.com/producto/hotel-en-venta-cerca-de-la-playa-en-puerto-escondido/
[16/78] https://www.vivamexicoinmobiliaria.com/producto/casa-palmeras-en-venta-en-puerto-escondido-con-alberca/
[17/78] https://www.vivamexicoinmobiliaria.com/producto/casa-santorini-inversion-frente-al-mar-en-punta-zicatela/
[18/78] https://www.vivamexicoinmobiliaria.com/producto/casa-pacifico-residencia-de-lujo-frente-al-mar-en-puerto-escondido/
[19/78] https://www.vivamexicoinmobiliaria.com/producto/casa-oaxaca-beach-en-rancho-neptuno/
[20/78] https://www.vivamexicoinmobiliaria.com/producto/casa-monte-alban-a-minutos-del-aeropuerto/
[21/78] https://www.vivamexicoinmobiliaria.com/producto/mezcalera-casas-boutique-en-la-punta-zicatela-desde-7-2-mdp/
[22/78] https://www.vivamexicoinmobiliaria.com/producto/villa-carelli-exclusividad-y-elegancia-en-puerto-escondido/
[23/78] https://www.vivamexicoinmobiliaria.com/producto/casa-ventanilla-frente-al-mar-en-venta-en-los-naranjos-puerto-escondido/
[24/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-frente-a-playa-rancho-neptuno/
[25/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-playa-ventanilla-tonameca/
[26/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-punta-zicatela-puerto-escondido/
[27/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-playa-aragon/
[28/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-fracc-colinas-del-mar/
[29/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-la-playa-zicatela-281m2/
[30/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-punta-zicatela-vista-al-mar/
[31/78] https://www.vivamexicoinmobiliaria.com/producto/terrenos-en-playa-agua-blanca-cerca-del-mar-vista-al-mar/
[32/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-venta-playa-el-tomatal-oaxaca/
[33/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-playa-puerto-angel-el-faro-vista-al-mar/
[34/78] https://www.vivamexicoinmobiliaria.com/producto/terrenos-en-la-barra-colotepec-cerca-de-la-playa/
[35/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-playa-palmarito-cerca-de-puerto-escondido/
[36/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-con-vista-al-mar-en-puerto-escondido/
[37/78] https://www.vivamexicoinmobiliaria.com/producto/terrenos-en-barra-navidad-puerto-escondido-2500m2/
[38/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-beachfront-en-el-puertecito-oaxaca/
[39/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-playa-barra-colotepec-200m2/
[40/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-playa-san-agustiillo/
[41/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-400-m%c2%b2-en-agua-blanca-puerto-escondido/
[42/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-beachfront-en-playa-zicatela/
[43/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-frente-al-mar-en-playa-el-tomatal/
[44/78] https://www.vivamexicoinmobiliaria.com/producto/terrenos-en-bacocho-puerto-escondido-desde-3-2-m/
[45/78] https://www.vivamexicoinmobiliaria.com/producto/terrenos-en-carrizalillo-puerto-escondido-desde-4-2-m/
[46/78] https://www.vivamexicoinmobiliaria.com/producto/hectarea-en-barra-de-cuatunalco-desde-2250000/
[47/78] https://www.vivamexicoinmobiliaria.com/producto/lotes-en-playa-el-puertecito/
[48/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-fraccionamiento-delfines-zicatela/
[49/78] https://www.vivamexicoinmobiliaria.com/producto/lotes-en-fracc-delfines-puerto-escondido-copia/
[50/78] https://www.vivamexicoinmobiliaria.com/producto/lotes-en-fracc-delfines-puerto-escondido/
[51/78] https://www.vivamexicoinmobiliaria.com/producto/lote-en-manzanillo-reef-cerca-al-mar-copia/
[52/78] https://www.vivamexicoinmobiliaria.com/producto/lote-en-manzanillo-reef-cerca-al-mar/
[53/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-playa-plataforma-744-m%c2%b2-en-oaxaca/
[54/78] https://www.vivamexicoinmobiliaria.com/producto/lotes-en-venta-playa-plataforma-oaxaca/
[55/78] https://www.vivamexicoinmobiliaria.com/producto/terrenos-en-venta-en-puerto-escondido-desde-6800-m%c2%b2/
[56/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-venta-mazunte/
[57/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-con-vista-en-playa-mermejita-1500-m%c2%b2/
[58/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-venta-en-playa-mermejita-de-2423-m2-con-vista-al-mar/
[59/78] https://www.vivamexicoinmobiliaria.com/producto/lotes-oaxtuxtla-en-la-barra-colotepec-oaxaca/
[60/78] https://www.vivamexicoinmobiliaria.com/producto/terrenos-tierra-blanca-en-santa-maria-colotepec/
[61/78] https://www.vivamexicoinmobiliaria.com/producto/fraccionamiento-esperanza-verde-terreno-exclusivo-junto-al-aeropuerto-de-puerto-escondido/
[62/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-venta-en-playa-palmarito-oaxaca-frente-al-mar/
[63/78] https://www.vivamexicoinmobiliaria.com/producto/residencial-don-goyo-lotes-en-desarrollo-privado-en-punta-zicatela-desde-400-m%c2%b2/
[64/78] https://www.vivamexicoinmobiliaria.com/producto/casa-frente-al-mar-en-venta-en-playa-tomatal-oaxaca/
[65/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-venta-en-playa-el-venado-con-vista-al-mar/
[66/78] https://www.vivamexicoinmobiliaria.com/producto/villas-boutique-preventa-vista-al-mar-and-art/
[67/78] https://www.vivamexicoinmobiliaria.com/producto/casa-mia-loft-casa-independiente-barra-colotepec/
[68/78] https://www.vivamexicoinmobiliaria.com/producto/departamentos-orliving-vista-al-mar-punta-de-zicatela/
[69/78] https://www.vivamexicoinmobiliaria.com/producto/casa-selva-blanca-lujo-arquitectura-y-playa/
[70/78] https://www.vivamexicoinmobiliaria.com/producto/preventa-manava-lofts-en-puerto-escondido-oaxaca/
[71/78] https://www.vivamexicoinmobiliaria.com/producto/terrenos-en-venta-en-emporio-puerto-escondido-oaxaca/
[72/78] https://www.vivamexicoinmobiliaria.com/producto/terreno-en-venta-playa-el-puertocito-copia/
[73/78] https://www.vivamexicoinmobiliaria.com/producto/departamentos-en-preventa-en-punta-zicatela/
[74/78] https://www.vivamexicoinmobiliaria.com/producto/departamentos-en-la-punta-puerto-escondido/
[75/78] https://www.vivamexicoinmobiliaria.com/producto/rancho-de-las-estrellas-lotes-ecologicos-en-chacahua-oaxaca/
[76/78] https://www.vivamexicoinmobiliaria.com/producto/playa-jamaica-terrenos-en-palmarito-oaxaca/
[77/78] https://www.vivamexicoinmobiliaria.com/producto/casa-menara-departamentos-de-lujo-en-puerto-escondido/
[78/78] https://www.vivamexicoinmobiliaria.com/producto/sierra-azul-residences-en-puerto-escondido-vive-en-lo-alto-y-conecta-con-lo-esencial/
Número de columnas en vivamexico con detalles: 10

,oferta,precio_mxn,tipo,link,fuente,fecha_consulta,correo,asesor,contacto,zona
0,"Casa en Residencial Don Goyo, Punta Zicatela",8800000.0,casas y departamentos,https://www.vivamexicoinmobiliaria.com/product...,Viva Mexico Inmobiliaria,2026-04-06 02:20:09,contacto@vivamexicoinmobiliaria.com,Gabriela Valencia,+529541383288,La Punta Zicatela
1,"Casa Selva Mar, Playa San Agustinillo, Oaxaca",5500000.0,casas y departamentos,https://www.vivamexicoinmobiliaria.com/product...,Viva Mexico Inmobiliaria,2026-04-06 02:20:09,contacto@vivamexicoinmobiliaria.com,Gabriela Valencia,+529541383288,Playa San Agustinillo
2,"Departamento Altavista– Vista al mar, diseño y...",309000.0,casas y departamentos,https://www.vivamexicoinmobiliaria.com/product...,Viva Mexico Inmobiliaria,2026-04-06 02:20:09,contacto@vivamexicoinmobiliaria.com,Gabriela Valencia,+529541383288,La Barra
3,"Casa Punta del Cielo, Playa San Agustinillo, O...",25000000.0,casas y departamentos,https://www.vivamexicoinmobiliaria.com/product...,Viva Mexico Inmobiliaria,2026-04-06 02:20:09,contacto@vivamexicoinmobiliaria.com,Gabriela Valencia,+529541383288,Playa San Agustinillo
4,"Casa El Faro, Puerto Angel",13500000.0,casas y departamentos,https://www.vivamexicoinmobiliaria.com/product...,Viva Mexico Inmobiliaria,2026-04-06 02:20:09,contacto@vivamexicoinmobiliaria.com,Gabriela Valencia,+529541383288,Playa Puerto Ángel

In [151]:
url="https://grupoinmobiliariohersa.com/terrenos-en-venta"
r=requests.get(url, headers=headers)
soup=BeautifulSoup(r.text, "html.parser")

In [172]:
titulos = [t.get_text(strip=True) for t in soup.find_all("h4", attrs={"data-typography": "HeadingBeta"})]
precios = [p.get_text(strip=True) for p in soup.find_all("div", attrs={"data-ux": "Price"})]
superficie = [s.get_text(strip=True) for s in soup.find_all("div", attrs={"data-ux": "Text"}) if "m2" in s.get_text(strip=True)]
#Extrae solo el número que está antes de m2
superficie_m2 = []
for s in superficie:
    m = re.search(r"([\d,]+)\s*m2", s, re.I)
    if m:
        superficie_m2.append(m.group(1).replace(",", ""))
    else:
        superficie_m2.append(None)
#Crear DataFrame
hersa = pd.DataFrame({
    "oferta": titulos,
    "precio_mxn": precios,
    "metros_cuad_terreno": superficie_m2
})
#Añadir fuente y fecha de consulta
hersa["fuente"] = "Hersa"
hersa["fecha_consulta"] = pd.Timestamp.now()
#Limpiar precio
hersa['precio_mxn'] = hersa['precio_mxn'].str.replace(r'[^\d.]', '', regex=True)
hersa['link'] = "https://grupoinmobiliariohersa.com/terrenos-en-venta"
hersa

,oferta,precio_mxn,metros_cuad_terreno,fuente,fecha_consulta,link
0,Fraccionamiento El Mirador,380000.00,200,Hersa,2026-04-06 02:37:14.520312,https://grupoinmobiliariohersa.com/terrenos-en...
1,Fraccionamiento El Guaje,150000.00,200,Hersa,2026-04-06 02:37:14.520312,https://grupoinmobiliariohersa.com/terrenos-en...
2,Fraccionamiento Los Frutillos,250000.00,200,Hersa,2026-04-06 02:37:14.520312,https://grupoinmobiliariohersa.com/terrenos-en...
3,Fraccionamiento Las Parotas,250000.00,200,Hersa,2026-04-06 02:37:14.520312,https://grupoinmobiliariohersa.com/terrenos-en...
4,Residencial Pirámide del Sol,500000.00,200,Hersa,2026-04-06 02:37:14.520312,https://grupoinmobiliariohersa.com/terrenos-en...
5,Fraccionamiento La Aurora,180000.00,200,Hersa,2026-04-06 02:37:14.520312,https://grupoinmobiliariohersa.com/terrenos-en...
6,Fraccionamiento Hacienda Camino Real,280000.00,200,Hersa,2026-04-06 02:37:14.520312,https://grupoinmobiliariohersa.com/terrenos-en...
7,Colinas de Regadío,70000.00,200,Hersa,2026-04-06 02:37:14.520312,https://grupoinmobiliariohersa.com/terrenos-en...
8,Fraccionamiento Altos San Miguel,160000.00,200,Hersa,2026-04-06 02:37:14.520312,https://grupoinmobiliariohersa.com/terrenos-en...
9,Fraccionamiento Arcangel,200000.00,200,Hersa,2026-04-06 02:37:14.520312,https://grupoinmobiliariohersa.com/terrenos-en...

#### Bayside

In [153]:
##

cookies = {
    '_omappvp': 'HowieCVlykfMOWxPuqFNXD0iGfHwrqw3GnDU4GYBf2rt0EPMYqMeAj50d0rsDv94kYbdMMHDZN6M7M1agGVkWXasEwkiJnc3',
    'AMP_MKTG_8f1ede8e9c': 'JTdCJTdE',
    '_ga': 'GA1.2.1858225868.1773099937',
    'AMP_8f1ede8e9c': 'JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJkM2M4NTA4NC0wOGU2LTQxMjUtODA1OC05ZTE2MzllNGFhZGQlMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzczMTk0NDU3NzI0JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=',
    'PHPSESSID': '7p3b183pl4vf9bvsp9t6r5aar6',
    'iTracker360_2620': 'sou%3Ddirect%7Cmed%3Dnone%7Cter%3D-%7Ccon%3D-%7Ccam%3Ddirect%7Cref%3Dhttps%253A//baysiderealestate.com/advanced-search/%7Cfirstlpurl%3Dhttps%253A//baysiderealestate.com/advanced-search/%7Cgcl%3D%7Cmcl%3D%7Cfcl%3D%7Cgaclientid%3D%7Cfbp%3D%7Cfbc%3D%7Cleadsource%3Ddirect%7Cip%3D%7Ccustomfield1%3D-%7Ccustomfield2%3D-%7Ccustomfield3%3D-%7Ccustomfield4%3D-',
    '_gid': 'GA1.2.902275613.1774850255',
    'AMP_8f1ede8e9c': 'JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJkM2M4NTA4NC0wOGU2LTQxMjUtODA1OC05ZTE2MzllNGFhZGQlMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzczMTk0NDU3NzI0JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=',
}

headers = {
    'accept': 'application/json, text/javascript, */*; q=0.01',
    'accept-language': 'es-US,es-419;q=0.9,es;q=0.8',
    'content-type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'origin': 'https://baysiderealestate.com',
    'priority': 'u=1, i',
    'referer': 'https://baysiderealestate.com/advanced-search/',
    'sec-ch-ua': '"Chromium";v="146", "Not-A.Brand";v="24", "Google Chrome";v="146"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Windows"',
    'sec-fetch-dest': 'empty',
    'sec-fetch-mode': 'cors',
    'sec-fetch-site': 'same-origin',
    'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/146.0.0.0 Safari/537.36',
    'x-requested-with': 'XMLHttpRequest',
    # 'cookie': '_omappvp=HowieCVlykfMOWxPuqFNXD0iGfHwrqw3GnDU4GYBf2rt0EPMYqMeAj50d0rsDv94kYbdMMHDZN6M7M1agGVkWXasEwkiJnc3; AMP_MKTG_8f1ede8e9c=JTdCJTdE; _ga=GA1.2.1858225868.1773099937; AMP_8f1ede8e9c=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJkM2M4NTA4NC0wOGU2LTQxMjUtODA1OC05ZTE2MzllNGFhZGQlMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzczMTk0NDU3NzI0JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=; PHPSESSID=7p3b183pl4vf9bvsp9t6r5aar6; iTracker360_2620=sou%3Ddirect%7Cmed%3Dnone%7Cter%3D-%7Ccon%3D-%7Ccam%3Ddirect%7Cref%3Dhttps%253A//baysiderealestate.com/advanced-search/%7Cfirstlpurl%3Dhttps%253A//baysiderealestate.com/advanced-search/%7Cgcl%3D%7Cmcl%3D%7Cfcl%3D%7Cgaclientid%3D%7Cfbp%3D%7Cfbc%3D%7Cleadsource%3Ddirect%7Cip%3D%7Ccustomfield1%3D-%7Ccustomfield2%3D-%7Ccustomfield3%3D-%7Ccustomfield4%3D-; _gid=GA1.2.902275613.1774850255; AMP_8f1ede8e9c=JTdCJTIyZGV2aWNlSWQlMjIlM0ElMjJkM2M4NTA4NC0wOGU2LTQxMjUtODA1OC05ZTE2MzllNGFhZGQlMjIlMkMlMjJzZXNzaW9uSWQlMjIlM0ExNzczMTk0NDU3NzI0JTJDJTIyb3B0T3V0JTIyJTNBZmFsc2UlN0Q=',
}

data = {
    'action': 'wpestate_custom_ondemand_pin_load',
    'search_type': '3',
    'val_holder[]': [
        'all',
        'puerto-escondido',
        'all',
        'all',
        'all',
        '',
        'all',
        '0',
    ],
    'newpage': '0',
    'postid': '1',
    'halfmap': '1',
    'slider_min': '0',
    'slider_max': '7000000',
    'all_checkers': '',
    'filter_search_action10': '',
    'adv_location10': '',
    'filter_search_action11': '',
    'filter_search_categ11': '',
    'geo_lat': '',
    'geo_long': '',
    'geo_rad': '',
    'term_counter': 'NaN',
    'componentsbeds': '',
    'componentsbaths': '',
    'security': '162a19dc02',
}

response = requests.post('https://baysiderealestate.com/wp-admin/admin-ajax.php', cookies=cookies, headers=headers, data=data)
json_data = response.json()
json_data.keys()

dict_keys(['xxx', 'args', 'markers', 'no_results'])

In [154]:
propiedades_limpias = []

for m in json_data['markers']:
    # Extraer y limpiar la superficie (quitar comas y etiquetas HTML)
    superficie_raw = m[14]
    # Usamos regex para quedarnos solo con números y el punto decimal
    num_superficie = float(re.sub(r'[^\d.]', '', superficie_raw.split(' ')[0].replace(',', '')))
    
    # Conversión a metros cuadrados
    m2 = round(num_superficie * 0.092903, 2)
    
    # Armar el diccionario
    info = {
        "oferta": m[0].replace('%20', ' '), # Decodificar espacios URL
        "latitud": m[1],
        "longitud": m[2],
        "tipo": m[6],
        "link": m[9],
        "precio_usd": m[11],
        "cuartos": m[12],
        "banos": m[13],
        "metros_cuad_const": m2
    }
    propiedades_limpias.append(info)

bayside = pd.DataFrame(propiedades_limpias)
#Añadir fuente y fecha de consulta
bayside["fuente"] = "Bayside Real Estate"
bayside["fecha_consulta"] = pd.Timestamp.now()
bayside["link"] = bayside["link"].apply(requests.utils.unquote)
tipo_map = {
    "condos-apartments" : "Departamento",
    "studios"           : "Departamento",
    "loft"              : "Departamento",
    "single-family-home": "Casa",
    "villa"             : "Casa",
    "duplex"            : "Casa",
    "beachfront"        : "Casa",
    "oceanfront"        : "Casa",
    "land"              : "Terreno",
    "lot"               : "Terreno",
    "boutique-hotel"    : "Otro",
    "commercial"        : "Otro",
}

bayside["tipo"] = bayside["tipo"].map(tipo_map).fillna("Otro")
print("Total de registros extraídos:", len(bayside))
print("Número de columnas en bayside:", bayside.shape[1])
bayside.head()

Total de registros extraídos: 50
Número de columnas en bayside: 11

,oferta,latitud,longitud,tipo,link,precio_usd,cuartos,banos,metros_cuad_const,fuente,fecha_consulta
0,Eco Habitat 2 Bedroom Condo,15.857623,-97.070893,Departamento,https://baysiderealestate.com/properties/eco-h...,288000,2,2,148.92,Bayside Real Estate,2026-04-06 02:22:26.720468
1,Puerto Escondido Ocean View Hotel,15.862067,-97.069175,Otro,https://baysiderealestate.com/properties/puert...,1543000,27,27,439.99,Bayside Real Estate,2026-04-06 02:22:26.720468
2,Panorama Coastal Residences In Puerto Escondido,15.831972,-97.038722,Departamento,https://baysiderealestate.com/properties/panor...,96000,1,1,26.11,Bayside Real Estate,2026-04-06 02:22:26.720468
3,3 Bedroom Oceanfront Modern Condo,15.857502,-97.068987,Departamento,https://baysiderealestate.com/properties/3-bed...,669000,3,2,199.56,Bayside Real Estate,2026-04-06 02:22:26.720468
4,1 Bedroom Poolside Condo,15.821020,-97.031940,Departamento,https://baysiderealestate.com/properties/1-bed...,125000,1,1,49.98,Bayside Real Estate,2026-04-06 02:22:26.720468

In [155]:
def scrape_bayside(url, session):
    try:
        r = session.get(url, timeout=10)
        r.raise_for_status()
        soup = BeautifulSoup(r.text, "html.parser")

        # ── ASESOR ──
        asesor = None
        asesor_tag = soup.select_one("div.col-md-7.agent_details h3 a")
        if asesor_tag:
            asesor = asesor_tag.get_text(strip=True)

        # ── TELÉFONO ──
        telefono = None
        tel_tag = soup.select_one("div.agent_detail.agent_phone_class a[href^='tel:']")
        if tel_tag:
            telefono = tel_tag["href"].replace("tel:", "").strip()

        # ── CORREO ──
        correo = None
        correo_tag = soup.select_one("div.agent_detail.agent_email_class a[href^='mailto:']")
        if correo_tag:
            correo = correo_tag["href"].replace("mailto:", "").strip()

        return asesor, telefono, correo

    except Exception as e:
        print(f"  ✗ Error: {url} → {e}")
        return None, None, None


# ── Loop ─────────────────────────────────────────────────────
session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
})

asesores, telefonos, correos = [], [], []

for i, url in enumerate(bayside["link"]):
    print(f"[{i+1}/{len(bayside)}] {url}")
    asesor, telefono, correo = scrape_bayside(url, session)
    asesores.append(asesor)
    telefonos.append(telefono)
    correos.append(correo)
    time.sleep(1.5)

bayside = bayside.copy()
bayside.loc[:, "asesor"]   = asesores
bayside.loc[:, "contacto"] = telefonos
bayside.loc[:, "correo"]   = correos
print("Número de columnas en bayside con detalles:", bayside.shape[1])
bayside.head()

[1/50] https://baysiderealestate.com/properties/eco-habitat-2-bedroom-condo/
[2/50] https://baysiderealestate.com/properties/puerto-escondido-ocean-view-hotel/
[3/50] https://baysiderealestate.com/properties/panorama-coastal-residences-in-puerto-escondido/
[4/50] https://baysiderealestate.com/properties/3-bedroom-oceanfront-modern-condo/
[5/50] https://baysiderealestate.com/properties/1-bedroom-poolside-condo/
[6/50] https://baysiderealestate.com/properties/oceanfront-carrizalillo-2-bedroom-condo/
[7/50] https://baysiderealestate.com/properties/selva-blanca-coastal-condos/
[8/50] https://baysiderealestate.com/properties/puerto-escondido-coastal-home/
[9/50] https://baysiderealestate.com/properties/puerto-escondido-5-bedroom-pool-home/
[10/50] https://baysiderealestate.com/properties/beautiful-ocean-view-loft-in-puerto-escondido/
[11/50] https://baysiderealestate.com/properties/prime-coastal-lot-steps-to-the-beach/
[12/50] https://baysiderealestate.com/properties/rinconada-villa-with-rooftop-ocean-views/
[13/50] https://baysiderealestate.com/properties/ocean-view-puerto-escondido-studio/
[14/50] https://baysiderealestate.com/properties/oceanfront-puerto-escondido-2-bedroom-condo/
[15/50] https://baysiderealestate.com/properties/rinconada-commercial-space/
[16/50] https://baysiderealestate.com/properties/contemporary-2-bedroom-coastal-residence/
[17/50] https://baysiderealestate.com/properties/modern-1-bedroom-coastal-condo/
[18/50] https://baysiderealestate.com/properties/luxury-4-bedroom-beachfront-villa/
[19/50] https://baysiderealestate.com/properties/puerto-escondido-beachside-home/
[20/50] https://baysiderealestate.com/properties/rare-beach-lot-in-la-punta-zicatela/
[21/50] https://baysiderealestate.com/properties/ocean-view-puerto-escondido-duplex/
[22/50] https://baysiderealestate.com/properties/modern-beach-studio-in-puerto-escondido/
[23/50] https://baysiderealestate.com/properties/puerto-escondido-beach-lofts/
[24/50] https://baysiderealestate.com/properties/1-bed-la-punta-condo/
[25/50] https://baysiderealestate.com/properties/2-bed-la-punta-condo/
[26/50] https://baysiderealestate.com/properties/beachfront-villa-in-puerto-escondido/
[27/50] https://baysiderealestate.com/properties/1-bed-puerto-escondido-oasis/
[28/50] https://baysiderealestate.com/properties/la-escondida-villa/
[29/50] https://baysiderealestate.com/properties/puerto-escondido-beachfront-houses/
[30/50] https://baysiderealestate.com/properties/casa-huizache-beachfront-villa/
[31/50] https://baysiderealestate.com/properties/casa-mezquite-beachfront-villa/
[32/50] https://baysiderealestate.com/properties/casa-pochote-beachfront-villa/
[33/50] https://baysiderealestate.com/properties/2-bed-oceanfront-condo/
[34/50] https://baysiderealestate.com/properties/3-bedroom-carrizalillo-villa/
[35/50] https://baysiderealestate.com/properties/ocean-view-3-bedroom-villa/
[36/50] https://baysiderealestate.com/properties/2-bedroom-puerto-escondido-home/
[37/50] https://baysiderealestate.com/properties/fully-furnished-home-with-exclusive-amenities/
[38/50] https://baysiderealestate.com/properties/osaka-condos-la-punta/
[39/50] https://baysiderealestate.com/properties/grava-zicatela-condos/
[40/50] https://baysiderealestate.com/properties/4-bedroom-palmarito-home/
[41/50] https://baysiderealestate.com/properties/tabachin-la-punta-condos/
[42/50] https://baysiderealestate.com/properties/2-bedroom-la-punta-zicatela-house/
[43/50] https://baysiderealestate.com/properties/rancho-neptuno-puerto-escondido-lot/
[44/50] https://baysiderealestate.com/properties/punta-mar-2-bedroom-single-family-home-puerto-escondido/
[45/50] https://baysiderealestate.com/properties/for-sale-palmarito-lot-puerto-escondido/
[46/50] https://baysiderealestate.com/properties/direct-beach-access-puerto-escondido-condo/
[47/50] https://baysiderealestate.com/properties/eco-luxury-beachfront-villa/
[48/50] https://baysiderealestate.com/properties/cabeza-de-tortuga-oceanfront-villa-puerto-escondido/
[49/50] https://baysiderealestate.com/properties/casa-piedra-beachfront-retreat-in-puertecito/
[50/50] https://baysiderealestate.com/properties/1-bedroom-beachfront-condo-for-sale-la-punta-zicatela/
Número de columnas en bayside con detalles: 14

,oferta,latitud,longitud,tipo,link,precio_usd,cuartos,banos,metros_cuad_const,fuente,fecha_consulta,asesor,contacto,correo
0,Eco Habitat 2 Bedroom Condo,15.857623,-97.070893,Departamento,https://baysiderealestate.com/properties/eco-h...,288000,2,2,148.92,Bayside Real Estate,2026-04-06 02:22:26.720468,Brent May,958-587-4543,info@baysidehuatulco.com
1,Puerto Escondido Ocean View Hotel,15.862067,-97.069175,Otro,https://baysiderealestate.com/properties/puert...,1543000,27,27,439.99,Bayside Real Estate,2026-04-06 02:22:26.720468,Kevin Knochel,958-587-4543,info@baysidepuertoescondido.com
2,Panorama Coastal Residences In Puerto Escondido,15.831972,-97.038722,Departamento,https://baysiderealestate.com/properties/panor...,96000,1,1,26.11,Bayside Real Estate,2026-04-06 02:22:26.720468,Kevin Knochel,958-587-4543,info@baysidepuertoescondido.com
3,3 Bedroom Oceanfront Modern Condo,15.857502,-97.068987,Departamento,https://baysiderealestate.com/properties/3-bed...,669000,3,2,199.56,Bayside Real Estate,2026-04-06 02:22:26.720468,Kevin Knochel,958-587-4543,info@baysidepuertoescondido.com
4,1 Bedroom Poolside Condo,15.821020,-97.031940,Departamento,https://baysiderealestate.com/properties/1-bed...,125000,1,1,49.98,Bayside Real Estate,2026-04-06 02:22:26.720468,Kevin Knochel,958-587-4543,info@baysidepuertoescondido.com

#### Tabla final

In [181]:
df_final=pd.concat([mexhome_df, osanpuerto, realestatepuerto,century21,pxm,pincali_data,
                    gr8, matrona,puertoproperty,inmobisur,madre_ceiba,vivamexico,hersa,bayside], ignore_index=True)
print("Total de registros:", len(df_final))

Total de registros: 797

In [182]:
print("Número de columnas en df_final:", df_final.shape[1])
precio_num = pd.to_numeric(df_final["precio_mxn"], errors="coerce").fillna(
    pd.to_numeric(df_final["precio_usd"], errors="coerce")
)

metros_num = pd.to_numeric(df_final["metros_cuad_const"], errors="coerce").fillna(
    pd.to_numeric(df_final["metros_cuad_terreno"], errors="coerce")
).replace(0, pd.NA)

df_final["precio_mt2"] = precio_num / metros_num
df_final

Número de columnas en df_final: 23

,oferta,precio_usd,cuartos,metros_cuad_const,metros_cuad_terreno,banos,latitud,longitud,link,tipo,...,correo,contacto,piscina,estacionamiento,precio_mxn,vista_al_mar,detalle,lotes,inversionistas,precio_mt2
0,Vivo &#8211; Building F &#8211; 632,295000,2,,,2,NaN,NaN,https://mexhome.com/es/property/vivo-building-...,Departamento,...,vivianne@mexhome.com,+52 331 536 2681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Vivo &#8211; Building H &#8211; 833,685000,4,,,3,15.91563,-97.185896,https://mexhome.com/es/property/vivo-building-...,Departamento,...,vivianne@mexhome.com,+52 331 536 2681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Vivo &#8211; Villa Lots &#8211; 28,149000,,,,,15.915738,-97.182546,https://mexhome.com/es/property/vivo-villa-lot...,Terreno,...,vivianne@mexhome.com,+52 331 536 2681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,325 Vivo &#8211; Building C,128900,0,,,1,NaN,NaN,https://mexhome.com/es/property/325-vivo-build...,Departamento,...,vivianne@mexhome.com,+52 331 536 2681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Vivo &#8211; Building E &#8211; 531,425000,3,,,2,15.915336,-97.185159,https://mexhome.com/es/property/vivo-building-...,Departamento,...,vivianne@mexhome.com,+52 331 536 2681,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
792,Direct Beach Access Puerto Escondido Condo,590000,2,155.98,NaN,2.5,15.81852,-97.033116,https://baysiderealestate.com/properties/direc...,Departamento,...,info@baysidehuatulco.com,958-587-4543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3782.536223
793,Eco Luxury Villa,1600000,4,349.97,NaN,4.5,15.81905,-97.037401,https://baysiderealestate.com/properties/eco-l...,Casa,...,info@baysidehuatulco.com,958-587-4543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4571.820442
794,Cabeza de Tortuga Oceanfront Villa Puerto Esco...,1650000,5,475.01,NaN,6,15.763531,-96.894367,https://baysiderealestate.com/properties/cabez...,Casa,...,info@baysidehuatulco.com,958-587-4543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3473.611082
795,Casa Piedra Beachfront Retreat,1600000,11,9499.52,NaN,11.5,15.74059,-96.852751,https://baysiderealestate.com/properties/casa-...,Casa,...,info@baysidehuatulco.com,958-587-4543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,168.429563
796,1 Bedroom Beachfront Condo,249000,1,74.79,NaN,1,15.840169,-97.047847,https://baysiderealestate.com/properties/1-bed...,Casa,...,info@baysidehuatulco.com,958-587-4543,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3329.322102

In [183]:
#Ordenar columnas. Primero zona, oferta, tipo, precio_mxn, precio_usd, precio_mt2, metros_cuad_const, metros_cuad_terreno, cuartos, banos, latitud, longitud, asesor, contacto, correo, fuente, fecha_consulta, link
columnas_ordenadas = ["zona", "oferta", "tipo", "precio_mxn", "precio_usd", "precio_mt2",
                      "metros_cuad_const", "metros_cuad_terreno", "cuartos", "banos","piscina", "estacionamiento", "vista_al_mar", 
                      "lotes", "inversionistas",
                      "latitud", "longitud", "asesor", "contacto", "correo",
                      "fuente", "fecha_consulta", "link"]
df_final = df_final.reindex(columns=columnas_ordenadas)

In [184]:
#Guardar en excel
df_final.to_excel("puerto_escondido_real_estate_6abril2026.xlsx", index=False)